fxaa.enabled: 1;

ssao.enabled: 1;
ssao.samples: 20;
ssao.radius: 0.5;
ssao.power: 10.0;
ssao.denoise: 1.0;
ssao.occlusionBufferDetail: 1.0;

glow.enabled: 1;
glow.viewScale: 0.5;
glow.threshold: 0.0;
glow.intensity: 0.1;
glow.radius: 6;

hdr.tonemapper: "AgX_Punchy";
hdr.exposure: 1.0;
hdr.autoexposure: true;
hdr.keyValue: 0.5;
hdr.exposureAdaptationSpeed: 0.5;

vignette.enabled: true;
vignette.strength: 0.7;
vignette.size: [0.5, 0.3];
vignette.roundness: 1.0;
vignette.feathering: 0.4;

motionBlur.enabled: 1;
motionBlur.samples: 16;
motionBlur.framerate: 30;
motionBlur.randomness: 0.2;
motionBlur.minDistance: 0.01;
motionBlur.maxDistance: 0.5;
motionBlur.radialBlurAmount: 0.015;

lensDistortion.enabled: 1;
lensDistortion.scale: 0.95;
lensDistortion.dispersion: 0.1;

dof.enabled: 0;
dof.autofocus: 1;
dof.focalDepth: 1.5;
dof.focalLength: 5.0;
dof.fStop: 2.0;
dof.manual: 0;
dof.nearStart: 1.0;
dof.nearDistance: 5.0;
dof.farStart: 15.0;
dof.farDistance: 20.0;

filmGrain.enabled: 1;
filmGrain.colored: 1;

sharpening.enabled: 1;
sharpening.strength: 0.5;

lut.enabled: 0;
lut.file: "data/luts/001.png";
