// Logger settings
log.enabled: true;
log.level: "debug";
log.toStdout: true;
log.timestampTags: false;
log.levelTags: true;

// VFS settings
vfs.appDataFolder: ".chillwave_drive";

// Window settings (used in windowed mode)
window.width: 1280;
window.height: 720;
window.maximized: false;
window.x: "auto";
window.y: "auto";
window.borderless: false;
window.resizable: true;
window.hiDPI: true;
window.title: "Chillwave Drive";

// Display settings
fullscreen: false;
vsync: 1;
stepFrequency: 60;
hideConsole: false;

// Locale settings
locale: "en_US";

// OpenGL settings
gl.debugOutput: true;
gl.outputColorProfile: "sRGB";
gl.anisotropicFiltering: true;
gl.defaultTextureAnisotropy: 8;
gl.shaderCache.enabled: false;
