/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ai;

import std.math;
import dagon;
import vehicle;

/**
 * AI that drives a given Vehicle along the path of waypoints.
 */
class Autopilot: Owner
{
    Vector3f[] waypoints;
    
    Vehicle car;
    float lookaheadDistance = 30.0f;
    
    bool active = true;
    
    // A visibility window of forward segments.
    size_t maxSegmentsToSearch = 30;
    
    size_t currentSegmentIndex = 0;
    float maxSpeed = 50.0f;
    float steeringForce = 10.0f;
    float maxLateralAcceleration = 5.0f;
    
    bool isIdle = true;
    bool isRecovering = false;
    double stuckTimer = 0.0;
    double recoveryTimer = 0.0;
    Vector3f targetPoint = Vector3f(0.0f, 0.0f, 0.0f);
    float curvature = 0.0f;
    float steeringInput = 0.0f;
    
    this(Vehicle controlledCar, Owner owner)
    {
        super(owner);
        this.car = controlledCar;
    }
    
    void start()
    {
        isIdle = false;
    }
    
    void stop()
    {
        isIdle = true;
    }
    
    void update(Time t)
    {
        if (!active)
            return;
        
        if (isIdle)
        {
            car.idle();
            return;
        }
        
        Vector3f carPosition = car.position;
        Vector3f carDirection = car.longitudinalAxis;
        float carSpeed = car.speed;
        
        targetPoint = calcTargetPoint(carPosition);
        
        curvature = 0.0f;
        float steeringAngle = calculateSteeringAngle(carPosition, carDirection, targetPoint, car.wheelbase, curvature);
        
        float maxSteeringAngle = degtorad(car.maxSteeringAngle);
        steeringInput = steeringForce * clamp(steeringAngle, -maxSteeringAngle, maxSteeringAngle) / maxSteeringAngle;
        steeringInput = clamp(steeringInput, -1.0f, 1.0f);
        
        float desiredThrottle = controlVehicleAcceleration(curvature, maxSpeed);
        
        bool inRecovery = handleRecovery(carSpeed, desiredThrottle, t.delta);

        if (!inRecovery)
        {
            car.manualSteer(steeringInput);
            
            if (desiredThrottle >= 0.0f)
                car.accelerate(1.0f, desiredThrottle);
            else
                car.idle();
                //car.accelerate(-1.0f, abs(desiredThrottle));
        }
    }
    
    Vector3f calcTargetPoint(Vector3f carPosition)
    {
        // Update the current segment (search for the closest point to the car within a small range).
        // Limit the search to the vicinity of the old index so it doesn't jump to the finish line
        size_t searchStart = (currentSegmentIndex > 2) ? currentSegmentIndex - 2 : 0;
        size_t searchEnd = currentSegmentIndex + 5;
        if (searchEnd >= waypoints.length) searchEnd = waypoints.length;

        float minD = float.max;
        size_t bestIdx = currentSegmentIndex;

        for (size_t i = searchStart; i < searchEnd; ++i)
        {
            float distSq = (carPosition.x - waypoints[i].x)^^2 + (carPosition.z - waypoints[i].z)^^2; // псевдокод
            if (distSq < minD)
            {
                minD = distSq;
                bestIdx = i;
            }
        }
        
        // Segment index is the index of the starting point of the segment
        if (bestIdx < waypoints.length - 1)
            currentSegmentIndex = bestIdx;
        else
            currentSegmentIndex = 0; // Looping the index when crossing the finish line

        return findLookaheadPoint(carPosition, lookaheadDistance, currentSegmentIndex);
    }
    
    Vector3f findLookaheadPoint(Vector3f carPosition, float lookaheadDist, size_t currentSegmentIndex)
    {
        if (waypoints.length < 2)
            return carPosition;

        size_t numWaypoints = waypoints.length;

        Vector3f bestLookaheadPt;
        bool found = false;
        float maxProgress = -1.0f; 
        size_t bestSegmentOrder = 0;

        for (size_t i = 0; i < maxSegmentsToSearch; ++i)
        {
            size_t idx1 = (currentSegmentIndex + i) % numWaypoints;
            size_t idx2 = (currentSegmentIndex + i + 1) % numWaypoints;

            Vector3f p1 = waypoints[idx1];
            Vector3f p2 = waypoints[idx2];

            float dx = p2.x - p1.x;
            float dz = p2.z - p1.z;

            float fx = p1.x - carPosition.x;
            float fz = p1.z - carPosition.z;

            float a = dx * dx + dz * dz;
            float b = 2.0f * (fx * dx + fz * dz);
            float c = (fx * fx + fz * fz) - (lookaheadDist * lookaheadDist);

            if (a == 0.0f) continue; 

            float discriminant = b * b - 4.0f * a * c;

            if (discriminant >= 0.0f)
            {
                discriminant = sqrt(discriminant);

                float t1 = (-b - discriminant) / (2.0f * a);
                float t2 = (-b + discriminant) / (2.0f * a);

                // We are looking for roots that fall strictly within the current segment [0, 1]
                float t = -1.0f;
                
                // We need the root that will take us further along the path.
                // On a looped track, we iterate from the nearest segments to the farthest ones.
                // Therefore, we take the largest valid t on the current segment.
                if (t2 >= 0.0f && t2 <= 1.0f) t = t2;
                else if (t1 >= 0.0f && t1 <= 1.0f) t = t1;

                if (t >= 0.0f)
                {
                    // It is critical to select a point that is on the farthest
                    // segment of those being viewed (i is the distance index from the car)
                    if (!found || i > bestSegmentOrder || (i == bestSegmentOrder && t > maxProgress))
                    {
                        maxProgress = t;
                        bestSegmentOrder = i;
                        
                        bestLookaheadPt.x = p1.x + t * dx;
                        bestLookaheadPt.z = p1.z + t * dz;
                        bestLookaheadPt.y = p1.y + t * (p2.y - p1.y); 
                        found = true;
                    }
                }
            }
        }

        // If an intersection is found in the visibility window, return it
        if (found) return bestLookaheadPt;

        // Fallback. Extrapolate the point strictly from the current segment forward, without jumping backwards
        size_t idx1 = currentSegmentIndex % numWaypoints;
        size_t idx2 = (currentSegmentIndex + 1) % numWaypoints;

        Vector3f p1 = waypoints[idx1];
        Vector3f p2 = waypoints[idx2];
        
        float dx = p2.x - p1.x;
        float dz = p2.z - p1.z;
        float segLength = sqrt(dx * dx + dz * dz);

        Vector3f fallbackPt;
        if (segLength > 0.0f)
        {
            float t = ((carPosition.x - p1.x) * dx + (carPosition.z - p1.z) * dz) / (segLength * segLength);
            if (t < 0.0f) t = 0.0f;
            if (t > 1.0f) t = 1.0f;

            float deltaT = lookaheadDist / segLength;
            float finalT = t + deltaT;
            
            if (finalT > 1.0f) 
            {
                // Move the remainder to the next segment in the loop
                float remainingDist = (finalT - 1.0f) * segLength;
                size_t nextIdx2 = (idx2 + 1) % numWaypoints;
                Vector3f np1 = waypoints[idx2];
                Vector3f np2 = waypoints[nextIdx2];
                float ndx = np2.x - np1.x;
                float ndz = np2.z - np1.z;
                float nSegLength = sqrt(ndx * ndx + ndz * ndz);
                
                if (nSegLength > 0.0f) {
                    float nextT = remainingDist / nSegLength;
                    if (nextT > 1.0f) nextT = 1.0f;
                    fallbackPt.x = np1.x + nextT * ndx;
                    fallbackPt.z = np1.z + nextT * ndz;
                    fallbackPt.y = np1.y + nextT * (np2.y - np1.y);
                    return fallbackPt;
                }
            }

            fallbackPt.x = p1.x + finalT * dx;
            fallbackPt.z = p1.z + finalT * dz;
            fallbackPt.y = p1.y + finalT * (p2.y - p1.y);
        }
        else
        {
            fallbackPt = p1;
        }

        return fallbackPt;
    }
    
    float calculateSteeringAngle(
        Vector3f carPosition,
        Vector3f carDirection,
        Vector3f targetPoint,
        float wheelbase,
        out float curvature)
    {
        // Get the vector from the car to the target point on the XZ plane
        float vX = targetPoint.x - carPosition.x;
        float vZ = targetPoint.z - carPosition.z;
        
        float lookaheadDist = sqrt(vX * vX + vZ * vZ);
        if (lookaheadDist == 0.0f) return 0.0f;

        // Find the global angle of direction to the target and the global angle of the car
        float angleToTarget = atan2(vX, vZ);
        float carFacingAngle = atan2(carDirection.x, carDirection.z);
        
        // Relative angle between the vehicle's direction and the target
        float alpha = angleToTarget - carFacingAngle;

        // Normalize the alpha angle to [-PI, PI] to avoid sharp turns
        import std.math : PI;
        while (alpha > PI)  alpha -= 2.0f * PI;
        while (alpha < -PI) alpha += 2.0f * PI;

        // Target arc curvature
        float kappa = (2.0f * sin(alpha)) / lookaheadDist;
        curvature = kappa;

        // Convert the curvature into the steering angle of the front wheels
        float steeringAngle = atan2(kappa * wheelbase, 1.0f);

        return steeringAngle;
    }
    
    float controlVehicleAcceleration(float kappa, float maxSpeed)
    {
        float currentSpeed = car.speed;
        
        float targetSpeed = maxSpeed;
        float absKappa = abs(kappa);

        // Calculate safe cornering speed
        if (absKappa > 0.001f)
        {
            float safeSpeed = sqrt(maxLateralAcceleration / absKappa);
            if (safeSpeed < targetSpeed) {
                targetSpeed = safeSpeed;
            }
        }

        // Minimum threshold to prevent the car from stopping completely
        if (targetSpeed < 5.0f) targetSpeed = 5.0f;

        float speedError = targetSpeed - currentSpeed;

        // Pedal sensitivity constants
        float Kp_gas = 0.3f;
        float Kp_brake = 0.01f;

        if (speedError > 0.0f)
        {
            // If the car goes slower than we need, then accelerate forward
            float throttleValue = clamp(speedError * Kp_gas, 0.0f, 1.0f);
            return throttleValue;
        }
        else
        {
            // Sowing down. If the car goes too fast, use brake/reverse
            float brakeForce = -clamp(abs(speedError) * Kp_brake, 0.0f, 1.0f);
            return brakeForce;
        }
    }
    
    /**
     * Checks the car's status and, if necessary, takes control to resolve a deadlock (reverses and turns around).
     * Returns true if the car is in recovery mode (at this point, Pure Pursuit should be disabled).
     */
    bool handleRecovery(float currentSpeed, float targetThrottle, double deltaTime)
    {
        // TODO: make configurable
        const float STUCK_SPEED_THRESHOLD = 0.75f; // Speed ​​below which we consider the car to be stationary (m/s)
        const float STUCK_TIME_TRIGGER = 0.5f;    // How many seconds do we wait before reversing
        const float RECOVERY_DURATION = 3.0f;     // How many seconds to reverse

        // Step 1: detect the stuck
        if (!isRecovering)
        {
            // If the AI ​​wants to drive forward, but the car's speed is almost zero
            if (targetThrottle > 0.2f && abs(currentSpeed) < STUCK_SPEED_THRESHOLD)
            {
                stuckTimer += deltaTime;
                if (stuckTimer >= STUCK_TIME_TRIGGER)
                {
                    // The car definitely got stuck! Activate recovery mode
                    isRecovering = true;
                    recoveryTimer = RECOVERY_DURATION;
                    stuckTimer = 0.0;
                }
            }
            else
            {
                // If the car is moving, smoothly reset the stuck timer
                if (stuckTimer > 0.0)
                    stuckTimer -= deltaTime;
            }
        }

        // Step 2: recovery (reversing)
        if (isRecovering)
        {
            recoveryTimer -= deltaTime;

            if (recoveryTimer <= 0.0f)
            {
                // Time's up, disable recovery mode and return control to Pure Pursuit
                isRecovering = false;
                stuckTimer = 0.0;
                return false;
            }

            car.accelerate(-1.0f, 0.7f);

            // TODO: steering
            // We don't just need to drive backwards, but also steer in the opposite direction
            // from the target point to turn the rear of the car into the open space.
            car.manualSteer(-1.0f);

            return true;
        }

        return false;
    }
}
