/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module car;

import dlib.text.str;
import dlib.serialization.json;

import dagon;
import dagon.ext.newton;
import vehicle;
import wheel;

class JSONAsset: Asset
{
    String str;
    JSONDocument doc;
    
    this(Owner o)
    {
        super(o);
    }

    ~this()
    {
        if (doc)
        {
            Delete(doc);
            doc = null;
        }
        if (str.length)
            str.free();
    }

    override bool loadThreadSafePart(string filename, InputStream istrm, ReadOnlyFileSystem fs, AssetManager mngr)
    {
        str = String(istrm);
        return true;
    }
    
    override bool loadThreadUnsafePart()
    {
        doc = New!JSONDocument(str);
        return true;
    }

    override void release()
    {
    }
}

float jsonPropFloat(JSONValue val, string name, float defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asNumber;
    else
        return defaultValue;
}

uint jsonPropUInt(JSONValue val, string name, uint defaultValue)
{
    if (name in val.asObject)
        return cast(uint)val.asObject[name].asNumber;
    else
        return defaultValue;
}

string jsonPropString(JSONValue val, string name, string defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asString;
    else
        return defaultValue;
}

Vector3f jsonPropVector(JSONValue val, string name, Vector3f defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asVector;
    else
        return defaultValue;
}

struct CarAsset
{
    JSONAsset aCar;
    GLTFAsset aChassis;
    GLTFAsset aWindows;
    Array!GLTFAsset aWheels;
    Texture shadowTexture;
    
    void free()
    {
        if (aWheels.length)
            aWheels.free();
    }
}

struct GLTFInstancedPrimitive
{
    GLTFMeshPrimitive geometry;
    Material material;
}

class GLTFGeometryInstance: Owner, Drawable
{
    Array!GLTFInstancedPrimitive instancedPrimitives;
    
    this(GLTFAsset asset, Owner owner)
    {
        super(owner);
        
        foreach(mesh; asset.meshes.data)
        {
            foreach(primitive; mesh.primitives)
            {
                auto prInstance = GLTFInstancedPrimitive(primitive, null);
                instancedPrimitives.append(prInstance);
            }
        }
    }
    
    ~this()
    {
        instancedPrimitives.free();
    }
    
    void render(GraphicsState* state)
    {
        GraphicsState newState = *state;
        foreach(primitive; instancedPrimitives)
        {
            auto geom = primitive.geometry;
            
            if (primitive.material)
                primitive.material.bind(&newState);
            else if (geom.material)
                geom.material.bind(&newState);

            newState.shader.bindParameters(&newState);

            geom.render(&newState);

            newState.shader.unbindParameters(&newState);

            if (primitive.material)
                primitive.material.unbind(&newState);
            else if (geom.material)
                geom.material.unbind(&newState);

        }
    }
}

class Car: Owner
{
    /// Underlying vehicle physics model.
    Vehicle vehicle;
    
    ///
    NewtonCompoundShape chassisShape;
    
    ///
    Vector3f startPosition;
    
    ///
    float startTurnAngle = 0.0f;
    
    ///
    float mass;
    
    ///
    Vector3f inertia;
    
    ///
    float suspensionMaxLength = 0.3f;
    
    ///
    float suspensionStiffness = 100.0f;
    
    ///
    float suspensionDamping = 10.0f;
    
    /// 
    Entity eCar;
    
    ///
    String name;
    
    ///
    bool isPlayer = false;
    
    ///
    Array!Entity eWheels;
    
    ///
    GLTFGeometryInstance chassisGeometry;
    
    ///
    Material carPaintMaterial;
    
    ///
    bool headlightsOn = true;
    
    ///
    float headlightsEnergy = 10.0f;
    
    ///
    float brakelightsEnergy = 5.0f;
    
    ///
    Material headlightsMaterial;
    
    ///
    Material brakelightsMaterial;
    
    ///
    Light light1;
    
    ///
    Light light2;
    
    ///
    float brakeHysteresisTimer = 0.0f;
    
    ///
    bool brakeHysteresis = false;
    
    ///
    bool raceStarted = false;
    
    ///
    bool finished = false;
    
    ///
    size_t trackSegmentIndex = 0;
    
    ///
    uint laps = 0;
    
    ///
    double raceTime = 0.0;
    
    ///
    double lapTime = 0.0;
    
    ///
    double bestLapTime = 0.0;
    
    ///
    uint racePosition = 0;
    
    this(Scene scene, NewtonPhysicsWorld physicsWorld, CarAsset* asset, Vector3f position, float turnAngle, Owner owner)
    {
        super(owner);
        
        startPosition = position;
        startTurnAngle = turnAngle;
        name = "Unknown";
        
        carPaintMaterial = scene.addMaterial();
        carPaintMaterial.roughnessFactor = 0.01f;
        
        headlightsMaterial = scene.addMaterial();
        headlightsMaterial.emissionFactor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        if (headlightsOn)
            headlightsMaterial.emissionEnergy = headlightsEnergy;
        else
            headlightsMaterial.emissionEnergy = 0.0f;
        
        brakelightsMaterial = scene.addMaterial();
        brakelightsMaterial.emissionFactor = Color4f(1.0f, 0.0f, 0.0f, 1.0f);
        if (headlightsOn)
            brakelightsMaterial.emissionEnergy = brakelightsEnergy;
        else
            brakelightsMaterial.emissionEnergy = 0.0f;
        
        eCar = scene.addEntity();
        eCar.position = startPosition;
        eCar.turn(startTurnAngle);
        eCar.blurMask = 0.0f;
        
        if (asset.shadowTexture)
        {
            auto eCarShadow = scene.addEntity(eCar);
            eCarShadow.drawable = New!ShapeBox(Vector3f(1.0f, 1.0f, 1.0f), scene.assetManager);
            eCarShadow.decal = true;
            eCarShadow.castShadow = false;
            eCarShadow.position = Vector3f(0.0f, 0.0f, 0.0f);
            eCarShadow.material = scene.addMaterial();
            asset.shadowTexture.enableRepeat = false;
            eCarShadow.material.baseColorTexture = asset.shadowTexture;
            eCarShadow.material.roughnessFactor = 1.0f;
            eCarShadow.material.blendMode = Transparent;
            eCarShadow.material.depthWrite = false;
            eCarShadow.material.useCulling = false;
            eCarShadow.material.outputColor = true;
            eCarShadow.material.outputPBR = true;
            eCarShadow.material.outputNormal = false;
            eCarShadow.material.outputEmission = false;
            eCarShadow.scaling = Vector3f(1.4f, 2.0f, 3.0f);
            eCarShadow.dynamic = true;
        }
        
        auto root = asset.aCar.doc.root;
        
        if ("chassis" in root.asObject)
        {
            auto chassis = root.asObject["chassis"].asObject;
            
            chassisGeometry = New!GLTFGeometryInstance(asset.aChassis, this);
            eCar.drawable = chassisGeometry;
            
            makeChassisMaterialUnique(asset.aChassis, asset.aCar, "paint", chassisGeometry, carPaintMaterial);
            makeChassisMaterialUnique(asset.aChassis, asset.aCar, "headlights", chassisGeometry, headlightsMaterial);
            makeChassisMaterialUnique(asset.aChassis, asset.aCar, "brakelights", chassisGeometry, brakelightsMaterial);
            
            if ("hitboxes" in chassis)
            {
                if (chassis["hitboxes"].asArray.length > 0)
                {
                    Array!NewtonCollisionShape hitboxShapes;
                    foreach(hitbox; chassis["hitboxes"].asArray)
                    {
                        Vector3f hitboxSize = jsonPropVector(hitbox, "size", Vector3f(1.0f, 1.0f, 1.0f));
                        Vector3f hitboxPosition = jsonPropVector(hitbox, "position", Vector3f(0.0f, 0.0f, 0.0f));
                        auto shape = New!NewtonBoxShape(hitboxSize, physicsWorld);
                        shape.setTransformation(translationMatrix(hitboxPosition));
                        hitboxShapes.append(shape);
                    }
                    chassisShape = New!NewtonCompoundShape(hitboxShapes.data, physicsWorld);
                }
            }
            else
                logWarning("\"hitboxes\" not specified");
        }
        
        if (asset.aWindows)
        {
            auto eWindows = scene.addEntity(eCar);
            auto dg = New!DrawableGroup(scene.assetManager);
            foreach(mesh; asset.aWindows.meshes.data)
            {
                dg.add(mesh);
            }
            eWindows.drawable = dg;
            eWindows.transparent = true;
            eWindows.castShadow = false;
            eWindows.blurMask = 0.0f;
        }
        
        mass = jsonPropFloat(root, "mass", 1500.0f);
        inertia = jsonPropVector(root, "inertia", Vector3f(1.0f, 1.0f, 1.0f));
        
        vehicle = New!Vehicle(physicsWorld, eCar, chassisShape, mass, 1);
        vehicle.setInertiaCoefficients(mass, inertia);
        vehicle.chassisBody.centerOfMass = jsonPropVector(root, "centerOfMass", Vector3f(0.0f, 0.0f, 0.0f));
        vehicle.maxSteeringAngle = jsonPropFloat(root, "maxSteeringAngle", 45.0f);
        vehicle.maxTorque = jsonPropFloat(root, "maxTorque", 500.0f);
        vehicle.arcadeSteering = true;
        
        if ("wheels" in root.asObject)
        {
            auto wheels = root.asObject["wheels"].asArray;
            foreach(i, wheel; wheels)
            {
                auto aWheel = asset.aWheels[i];
                
                float wheelRadius = jsonPropFloat(wheel, "radius", 0.337f);
                float facing = jsonPropFloat(wheel, "facing", -1.0f);
                
                Vector3f suspensionPosition = Vector3f(-0.75f, 0.2f, +1.35f);
                suspensionMaxLength = 0.3f;
                suspensionStiffness = 100.0f;
                suspensionDamping = 10.0f;
                
                if ("suspension" in wheel.asObject)
                {
                    auto suspension = wheel.asObject["suspension"];
                    suspensionPosition = jsonPropVector(suspension, "position", suspensionPosition);
                    suspensionMaxLength = jsonPropFloat(suspension, "maxLength", suspensionMaxLength);
                    suspensionStiffness = jsonPropFloat(suspension, "stiffness", suspensionStiffness);
                    suspensionDamping = jsonPropFloat(suspension, "damping", suspensionDamping);
                }
                
                float tyreLateralFriction = 0.75f;
                float tyreLongitudinalFriction = 1.0f;
                
                if ("tyre" in wheel.asObject)
                {
                    auto tyre = wheel.asObject["tyre"];
                    tyreLateralFriction = jsonPropFloat(tyre, "lateralFriction", tyreLateralFriction);
                    tyreLongitudinalFriction = jsonPropFloat(tyre, "longitudinalFriction", tyreLongitudinalFriction);
                }
                
                Wheel pWheel = vehicle.addWheel(suspensionPosition, wheelRadius, facing);
                pWheel.load = jsonPropFloat(wheel, "loadSplit", 0.25f);
                pWheel.torqueSplitRatio = jsonPropFloat(wheel, "torqueSplit", 0.0f);
                pWheel.camberAngle = jsonPropFloat(wheel, "camberAngle", 0.0f);
                pWheel.lateralDynamicFrictionCoefficient = tyreLateralFriction;
                pWheel.longitudinalDynamicFrictionCoefficient = tyreLongitudinalFriction;
                pWheel.suspension.maxLength = suspensionMaxLength;
                pWheel.suspension.stiffness = suspensionStiffness;
                pWheel.suspension.damping = suspensionDamping;
                
                Entity eWheel = scene.addEntity(eCar);
                auto dg = New!DrawableGroup(scene.assetManager);
                foreach(mesh; aWheel.meshes.data)
                {
                    dg.add(mesh);
                }
                eWheel.drawable = dg;
                eWheel.position = pWheel.localWheelPosition;
                eWheel.blurMask = 1.0f;
                eWheel.blurMaxVelocity = 0.018f;
                eWheels.append(eWheel);
            }
        }
        
        // Headlights (TODO: load from car asset)
        light1 = scene.addLight(LightType.Spot, eCar);
        light1.volumeRadius = 10.0f;
        light1.energy = 5.0f;
        light1.spotOuterCutoff = 45.0f;
        light1.position = Vector3f(-0.6f, 0.0f, 2.5f);
        light1.turn(180);
        
        light2 = scene.addLight(LightType.Spot, eCar);
        light2.volumeRadius = 10.0f;
        light2.energy = 5.0f;
        light2.spotOuterCutoff = 45.0f;
        light2.position = Vector3f(0.6f, 0.0f, 2.5f);
        light2.turn(180);
        
        light1.shining = headlightsOn;
        light2.shining = headlightsOn;
    }
    
    ~this()
    {
        eWheels.free();
        name.free();
    }
    
    void restart()
    {
        vehicle.reset(startPosition, rotationQuaternion!float(Axis.y, degtorad(startTurnAngle)));
        brakeHysteresisTimer = 0.0f;
        brakeHysteresis = false;
        raceStarted = false;
        finished = false;
        trackSegmentIndex = 0;
        laps = 0;
        raceTime = 0.0;
        lapTime = 0.0;
        bestLapTime = 0.0;
        racePosition = 0;
    }
    
    bool makeChassisMaterialUnique(GLTFAsset carModel, JSONAsset carConfig, string matType, GLTFGeometryInstance geomInstance, Material replaceWith)
    {
        auto root = carConfig.doc.root;
        
        JSONObject chassis;
        if ("chassis" in root.asObject)
            chassis = root.asObject["chassis"].asObject;
        else
        {
            logWarning("\"chassis\" object not specified");
            return false;
        }
        
        if ("materials" in chassis)
        {
            auto materials = chassis["materials"];
            if (matType in materials.asObject)
            {
                string matName = jsonPropString(materials, matType, "");
                if (matName.length)
                {
                    auto m = carModel.material(matName);
                    foreach(ref primitive; geomInstance.instancedPrimitives.data)
                    {
                        if (primitive.geometry.material is m)
                            primitive.material = replaceWith;
                    }
                }
            }
            else
            {
                logWarning("\"", matType, "\" material not specified");
                return false;
            }
        }
        else
        {
            logWarning("\"materials\" not specified");
            return false;
        }
        
        return true;
    }
    
    void toggleHeadlights()
    {
        headlightsOn = !headlightsOn;
        light1.shining = headlightsOn;
        light2.shining = headlightsOn;
        if (headlightsMaterial)
        {
            if (headlightsOn)
                headlightsMaterial.emissionEnergy = headlightsEnergy;
            else
                headlightsMaterial.emissionEnergy = 0.0f;
        }
    }
    
    void update(Time t)
    {
        // Rotate wheels
        foreach(i, w; eWheels)
        {
            w.position = vehicle.wheels[i].localWheelPosition;
            w.rotation = vehicle.wheels[i].localRotation;
        }
        
        vehicle.update(t);
        
        if (brakelightsMaterial)
        {
            if (vehicle.brake)
                brakeHysteresis = true;
            
            if (vehicle.brake || brakeHysteresis || headlightsOn)
                brakelightsMaterial.emissionEnergy = brakelightsEnergy;
            else
                brakelightsMaterial.emissionEnergy = 0.0f;
            
            if (brakeHysteresis)
            {
                if (brakeHysteresisTimer < 0.5f)
                    brakeHysteresisTimer += t.delta;
                else
                {
                    brakeHysteresisTimer = 0.0f;
                    brakeHysteresis = false;
                }
            }
        }
        
        if (raceStarted && !finished)
        {
            raceTime += t.delta;
            lapTime += t.delta;
        }
        
        size_t prevSegment = trackSegmentIndex;
        trackSegmentIndex = vehicle.track.getNearestSegmentIndex(trackSegmentIndex, vehicle.position);
        if (trackSegmentIndex == 0 && prevSegment == vehicle.track.waypoints.length - 2)
        {
            if (!finished)
            {
                laps++;
                if (laps == vehicle.track.numLaps)
                    finished = true;
                
                if (lapTime < bestLapTime || bestLapTime == 0.0)
                    bestLapTime = lapTime;
                lapTime = 0.0;
            }
        }
    }
    
    Vector3f position()
    {
        return vehicle.position;
    }
    
    float speedKMH()
    {
        return vehicle.speedKMH;
    }
    
    float steeringInput()
    {
        return vehicle.steeringInput;
    }
    
    float throttle()
    {
        return vehicle.throttle;
    }
    
    float clutch()
    {
        return vehicle.clutch;
    }
    
    uint gear()
    {
        return vehicle.gear;
    }
    
    float rpm()
    {
        return vehicle.rpm;
    }
    
    float lateralSlip()
    {
        return vehicle.lateralSlip;
    }
    
    float longitudinalSlip()
    {
        return vehicle.longitudinalSlip;
    }
    
    bool brake()
    {
        return vehicle.brake;
    }
}
