/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module car;

import dlib.serialization.json;
import dagon;
import dagon.ext.newton;
import vehicle;
import wheel;

class JSONAsset: Asset
{
    String str;
    JSONDocument doc;
    
    this(Owner o)
    {
        super(o);
    }

    ~this()
    {
        //release();
        if (doc)
        {
            Delete(doc);
            doc = null;
        }
        if (str.length)
            str.free();
    }

    override bool loadThreadSafePart(string filename, InputStream istrm, ReadOnlyFileSystem fs, AssetManager mngr)
    {
        str = String(istrm);
        //logInfo(str);
        //logInfo(str.length);
        //doc = New!JSONDocument(str);
        return true;
    }
    
    override bool loadThreadUnsafePart()
    {
        doc = New!JSONDocument(str);
        return true;
    }

    override void release()
    {
    }
}

float jsonPropFloat(JSONValue val, string name, float defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asNumber;
    else
        return defaultValue;
}

uint jsonPropUInt(JSONValue val, string name, uint defaultValue)
{
    if (name in val.asObject)
        return cast(uint)val.asObject[name].asNumber;
    else
        return defaultValue;
}

string jsonPropString(JSONValue val, string name, string defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asString;
    else
        return defaultValue;
}

Vector3f jsonPropVector(JSONValue val, string name, Vector3f defaultValue)
{
    if (name in val.asObject)
        return val.asObject[name].asVector;
    else
        return defaultValue;
}

struct CarAsset
{
    JSONAsset aCar;
    GLTFAsset aChassis;
    GLTFAsset aWindows;
    Array!GLTFAsset aWheels;
    Texture shadowTexture;
    
    void free()
    {
        if (aWheels.length)
            aWheels.free();
    }
}

class Car: Owner
{
    /// Underlying vehicle physics model.
    Vehicle vehicle;
    
    ///
    NewtonCompoundShape chassisShape;
    
    float mass;
    Vector3f inertia;
    float suspensionMaxLength = 0.3f;
    float suspensionStiffness = 100.0f;
    float suspensionDamping = 10.0f;
    
    /// 
    Entity eCar;
    
    ///
    Array!Entity eWheels;
    
    ///
    Material carPaintMaterial;
    
    bool headlightsOn = true;
    float headlightsEnergy = 10.0f;
    Material headlightsMaterial;
    Light light1, light2, light1_vol, light2_vol;
    
    this(Scene scene, NewtonPhysicsWorld physicsWorld, CarAsset* asset, Vector3f position, float turnAngle, Owner owner)
    {
        super(owner);
        
        //carPaintMaterial = scene.addMaterial();
        //carPaintMaterial.roughnessFactor = 0.01f;
        
        eCar = scene.addEntity();
        eCar.position = position; //Vector3f(0.0f, 0.8f, 0.0f);
        eCar.turn(turnAngle); //90.0f
        eCar.blurMask = 0.0f;
        
        if (asset.shadowTexture)
        {
            auto eCarShadow = scene.addEntity(eCar);
            eCarShadow.drawable = New!ShapeBox(Vector3f(1.0f, 1.0f, 1.0f), scene.assetManager);
            eCarShadow.decal = true;
            eCarShadow.castShadow = false;
            eCarShadow.position = Vector3f(0.0f, 0.0f, 0.0f);
            eCarShadow.material = scene.addMaterial();
            asset.shadowTexture.enableRepeat = false;
            eCarShadow.material.baseColorTexture = asset.shadowTexture;
            eCarShadow.material.blendMode = Transparent;
            eCarShadow.material.depthWrite = false;
            eCarShadow.material.useCulling = false;
            eCarShadow.material.roughnessFactor = 1.0f;
            eCarShadow.scaling = Vector3f(1.4f, 2.0f, 3.0f);
            eCarShadow.dynamic = true;
        }
        
        auto root = asset.aCar.doc.root;
        
        if ("chassis" in root.asObject)
        {
            auto chassis = root.asObject["chassis"].asObject;
            
            auto dg = New!DrawableGroup(scene.assetManager);
            foreach(mesh; asset.aChassis.meshes.data)
            {
                dg.add(mesh);
            }
            eCar.drawable = dg;
            
            if ("materials" in chassis)
            {
                auto materials = chassis["materials"];
                
                if ("headlights" in materials.asObject)
                {
                    string headlightsMaterialName = jsonPropString(materials, "headlights", "");
                    if (headlightsMaterialName.length)
                    {
                        headlightsMaterial = asset.aChassis.material(headlightsMaterialName);
                        headlightsMaterial.emissionFactor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
                        if (headlightsOn)
                            headlightsMaterial.emissionEnergy = headlightsEnergy;
                        else
                            headlightsMaterial.emissionEnergy = 0.0f;
                    }
                }
            }
            
            if ("hitboxes" in chassis)
            {
                if (chassis["hitboxes"].asArray.length > 0)
                {
                    Array!NewtonCollisionShape hitboxShapes;
                    foreach(hitbox; chassis["hitboxes"].asArray)
                    {
                        Vector3f hitboxSize = jsonPropVector(hitbox, "size", Vector3f(1.0f, 1.0f, 1.0f));
                        Vector3f hitboxPosition = jsonPropVector(hitbox, "position", Vector3f(0.0f, 0.0f, 0.0f));
                        auto shape = New!NewtonBoxShape(hitboxSize, physicsWorld);
                        shape.setTransformation(translationMatrix(hitboxPosition));
                        hitboxShapes.append(shape);
                    }
                    chassisShape = New!NewtonCompoundShape(hitboxShapes.data, physicsWorld);
                }
            }
            
            carPaintMaterial = asset.aChassis.material("paint");
            
            /*
            auto paintMaterial = asset.aChassis.material("paint");
            if (paintMaterial)
            {
                foreach(mesh; asset.aChassis.meshes.data)
                {
                    foreach(meshPrimitive; mesh.primitives)
                    {
                        if (meshPrimitive.material is paintMaterial)
                            meshPrimitive.material = carPaintMaterial;
                    }
                }
            }
            */
        }
        
        if (asset.aWindows)
        {
            auto eWindows = scene.addEntity(eCar);
            auto dg = New!DrawableGroup(scene.assetManager);
            foreach(mesh; asset.aWindows.meshes.data)
            {
                dg.add(mesh);
            }
            eWindows.drawable = dg;
            eWindows.transparent = true;
            eWindows.castShadow = false;
            eWindows.blurMask = 0.0f;
        }
        
        mass = jsonPropFloat(root, "facing", 1500.0f);
        inertia = jsonPropVector(root, "inertia", Vector3f(1.0f, 1.0f, 1.0f));
        
        vehicle = New!Vehicle(physicsWorld, eCar, chassisShape, mass, 1);
        vehicle.setInertia(mass, boxInertia(inertia, mass));
        vehicle.chassisBody.centerOfMass = jsonPropVector(root, "centerOfMass", Vector3f(0.0f, 0.0f, 0.0f));
        vehicle.maxSteeringAngle = jsonPropFloat(root, "maxSteeringAngle", 45.0f);
        vehicle.maxTorque = jsonPropFloat(root, "maxTorque", 500.0f);
        vehicle.arcadeSteering = true;
        
        if ("wheels" in root.asObject)
        {
            auto wheels = root.asObject["wheels"].asArray;
            foreach(i, wheel; wheels)
            {
                auto aWheel = asset.aWheels[i];
                
                float wheelRadius = jsonPropFloat(wheel, "radius", 0.337f);
                float facing = jsonPropFloat(wheel, "facing", -1.0f);
                
                Vector3f suspensionPosition = Vector3f(-0.75f, 0.2f, +1.35f);
                suspensionMaxLength = 0.3f;
                suspensionStiffness = 100.0f;
                suspensionDamping = 10.0f;
                
                if ("suspension" in wheel.asObject)
                {
                    auto suspension = wheel.asObject["suspension"];
                    suspensionPosition = jsonPropVector(suspension, "position", suspensionPosition);
                    suspensionMaxLength = jsonPropFloat(suspension, "maxLength", suspensionMaxLength);
                    suspensionStiffness = jsonPropFloat(suspension, "stiffness", suspensionStiffness);
                    suspensionDamping = jsonPropFloat(suspension, "damping", suspensionDamping);
                }
                
                float tyreLateralFriction = 0.75f;
                float tyreLongitudinalFriction = 1.0f;
                
                if ("tyre" in wheel.asObject)
                {
                    auto tyre = wheel.asObject["tyre"];
                    tyreLateralFriction = jsonPropFloat(tyre, "lateralFriction", tyreLateralFriction);
                    tyreLongitudinalFriction = jsonPropFloat(tyre, "longitudinalFriction", tyreLongitudinalFriction);
                }
                
                Wheel pWheel = vehicle.addWheel(suspensionPosition, wheelRadius, facing);
                pWheel.load = jsonPropFloat(wheel, "loadSplit", 0.25f);
                pWheel.torqueSplitRatio = jsonPropFloat(wheel, "torqueSplit", 0.0f);
                pWheel.camberAngle = jsonPropFloat(wheel, "camberAngle", 0.0f);
                pWheel.lateralDynamicFrictionCoefficient = tyreLateralFriction;
                pWheel.longitudinalDynamicFrictionCoefficient = tyreLongitudinalFriction;
                pWheel.suspension.maxLength = suspensionMaxLength;
                pWheel.suspension.stiffness = suspensionStiffness;
                pWheel.suspension.damping = suspensionDamping;
                
                Entity eWheel = scene.addEntity(eCar);
                auto dg = New!DrawableGroup(scene.assetManager);
                foreach(mesh; aWheel.meshes.data)
                {
                    dg.add(mesh);
                }
                eWheel.drawable = dg;
                eWheel.position = pWheel.localWheelPosition;
                eWheel.blurMask = 0.0f;
                eWheels.append(eWheel);
            }
        }
        
        // Headlights (TODO: load from car asset)
        light1 = scene.addLight(LightType.Spot, eCar);
        light1.volumeRadius = 10.0f;
        light1.energy = 5.0f;
        light1.spotOuterCutoff = 45.0f;
        light1.position = Vector3f(-0.6f, 0.0f, 2.5f);
        light1.turn(180);
        
        light2 = scene.addLight(LightType.Spot, eCar);
        light2.volumeRadius = 10.0f;
        light2.energy = 5.0f;
        light2.spotOuterCutoff = 45.0f;
        light2.position = Vector3f(0.6f, 0.0f, 2.5f);
        light2.turn(180);
        
        /*
        light1_vol = scene.addLight(LightType.AreaSphere, eCar);
        light1_vol.volumeRadius = 10.0f;
        light1_vol.energy = 0.2f;
        light1_vol.volumeRadius = 0.7f;
        light1_vol.scatteringEnabled = true;
        light1_vol.mediumDensity = 0.5f;
        light1_vol.position = Vector3f(-0.65f, 0.2f, 2.0f);
        
        light2_vol = scene.addLight(LightType.AreaSphere, eCar);
        light2_vol.volumeRadius = 10.0f;
        light2_vol.energy = 0.2f;
        light2_vol.volumeRadius = 0.7f;
        light2_vol.scatteringEnabled = true;
        light2_vol.mediumDensity = 0.5f;
        light2_vol.position = Vector3f(0.65f, 0.2f, 2.0f);
        */
        
        light1.shining = headlightsOn;
        light2.shining = headlightsOn;
        
        /*
        light1_vol.shining = headlightsOn;
        light2_vol.shining = headlightsOn;
        */
        
        // TODO
        /*
        auto eParticles = addEntity();
        particleSystem = New!ParticleSystem(eventManager, eParticles);
        
        // Dust particle systems
        auto mParticlesDust = addMaterial();
        mParticlesDust.baseColorTexture = aTexParticleDust.texture;
        mParticlesDust.blendMode = Transparent;
        mParticlesDust.depthWrite = false;
        mParticlesDust.sun = sun;
        mParticlesDust.opacity = 0.2f;
        mParticlesDust.useShadows = true;

        auto eParticlesRight = addEntity(eCar);
        emitterRight = New!Emitter(eParticlesRight, particleSystem, 30);
        eParticlesRight.position = Vector3f(-0.9f, 0.0f, -0.8f);
        emitterRight.minLifetime = 1.0f;
        emitterRight.maxLifetime = 3.0f;
        emitterRight.minSize = 0.5f;
        emitterRight.maxSize = 1.0f;
        emitterRight.minInitialSpeed = 0.2f;
        emitterRight.maxInitialSpeed = 0.2f;
        emitterRight.scaleStep = Vector2f(2, 2);
        emitterRight.material = mParticlesDust;
        eParticlesRight.castShadow = false;
        eParticlesRight.visible = true;

        auto eParticlesLeft = addEntity(eCar);
        emitterLeft = New!Emitter(eParticlesLeft, particleSystem, 30);
        eParticlesLeft.position = Vector3f(0.9f, 0.0f, -0.8f);
        emitterLeft.minLifetime = 1.0f;
        emitterLeft.maxLifetime = 3.0f;
        emitterLeft.minSize = 0.5f;
        emitterLeft.maxSize = 1.0f;
        emitterLeft.minInitialSpeed = 0.2f;
        emitterLeft.maxInitialSpeed = 0.2f;
        emitterLeft.scaleStep = Vector2f(2, 2);
        emitterLeft.material = mParticlesDust;
        eParticlesLeft.castShadow = false;
        eParticlesLeft.visible = true;
        */
    }
    
    ~this()
    {
        eWheels.free();
    }
    
    void toggleHeadlights()
    {
        headlightsOn = !headlightsOn;
        light1.shining = headlightsOn;
        light2.shining = headlightsOn;
        //light1_vol.shining = headlightsOn;
        //light2_vol.shining = headlightsOn;
        if (headlightsMaterial)
        {
            if (headlightsOn)
                headlightsMaterial.emissionEnergy = headlightsEnergy;
            else
                headlightsMaterial.emissionEnergy = 0.0f;
        }
    }
    
    void update(Time t)
    {
        // Rotate wheels
        foreach(i, w; eWheels)
        {
            w.position = vehicle.wheels[i].localWheelPosition;
            w.rotation = vehicle.wheels[i].localRotation;
        }
        
        vehicle.update(t);
    }
    
    Vector3f position()
    {
        return vehicle.position;
    }
    
    float speedKMH()
    {
        return vehicle.speedKMH;
    }
    
    float steeringInput()
    {
        return vehicle.steeringInput;
    }
    
    float throttle()
    {
        return vehicle.throttle;
    }
    
    float clutch()
    {
        return vehicle.clutch;
    }
    
    uint gear()
    {
        return vehicle.gear;
    }
    
    float rpm()
    {
        return vehicle.rpm;
    }
    
    float lateralSlip()
    {
        return vehicle.lateralSlip;
    }
    
    float longitudinalSlip()
    {
        return vehicle.longitudinalSlip;
    }
    
    bool brake()
    {
        return vehicle.brake;
    }
}
