/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module carselection;

import std.stdio;
import std.algorithm;

import dagon;
import dagon.ext.imgui;
import game;

class CarSelectionScene: Scene
{
    ChillwaveDriveGame game;
    Camera camera;
    
    TextureAsset selectionFrame;
    Entity frame;
    
    string[] carConfigs;
    
    size_t numCarThumbs = 2;
    float carThumbAspectRatio = 16.0f / 9.0f;
    uint carThumbWidth;
    uint carThumbHeight;
    TextureAsset[] thumbTextures;
    Entity[] carThumbs;
    bool initialized = false;
    
    size_t selectedCarIndex = 0;
    string selectedCarFilename;

    this(ChillwaveDriveGame game)
    {
        super(game);
        this.game = game;
        
        // TODO: read cars.json instead
        carConfigs = New!(string[])(numCarThumbs);
        thumbTextures = New!(TextureAsset[])(numCarThumbs);
    }
    
    ~this()
    {
        if (carConfigs.length)
            Delete(carConfigs);
        if (thumbTextures.length)
            Delete(thumbTextures);
        if (carThumbs.length)
            Delete(carThumbs);
    }

    override void beforeLoad()
    {
        selectionFrame = addTextureAsset("data/ui/car_selection_frame.png");
        
        // TODO: read cars.json instead
        thumbTextures[0] = addTextureAsset("data/cars/cc_050/cc_050_preview.webp");
        thumbTextures[1] = addTextureAsset("data/cars/goblin/goblin_preview.webp");
        
        carConfigs[0] = "data/cars/cc_050/cc_050.json";
        carConfigs[1] = "data/cars/goblin/goblin.json";
        selectedCarFilename = carConfigs[0];
    }
    
    override void onLoad(Time t, float progress)
    {
    }
    
    override void afterLoad()
    {
        camera = addCamera();
        
        auto hudShader = New!HUDShader(assetManager);
        
        auto quad = New!ShapeQuad(assetManager);
        
        // TODO: read cars.json instead
        carThumbs = New!(Entity[])(numCarThumbs);
        foreach(i; 0..carThumbs.length)
        {
            auto t = addEntityHUD();
            t.drawable = quad;
            t.material = addMaterial();
            t.material.shader = hudShader;
            t.material.depthWrite = false;
            t.material.useCulling = false;
            t.material.baseColorFactor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
            t.material.baseColorTexture = thumbTextures[i].texture;
            carThumbs[i] = t;
        }
        
        frame = addEntityHUD();
        frame.drawable = quad;
        frame.material = addMaterial();
        frame.material.shader = hudShader;
        frame.material.depthWrite = false;
        frame.material.useCulling = false;
        frame.material.blendMode = Transparent;
        frame.material.baseColorFactor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        frame.material.baseColorTexture = selectionFrame.texture;
        frame.visible = true;
        
        initialized = true;
        resizeThumbs(game.drawableWidth, game.drawableHeight);
        
        onReset();
    }
    
    override void onReset()
    {
        game.hudRenderer.passHUD.clear = true;
        game.renderer.activeCamera = camera;
        game.imgui.active = true;
    }
    
    override void onUpdate(Time t)
    {
        bool cursorSet = false;
        foreach(i, thumb; carThumbs)
        {
            if (eventManager.mouseX >= thumb.position.x && eventManager.mouseX < thumb.position.x + thumb.scaling.x &&
                eventManager.mouseY >= thumb.position.y && eventManager.mouseY < thumb.position.y + thumb.scaling.y)
            {
                game.setCursor(SystemCursor.Hand);
                cursorSet = true;
                break;
            }
        }
        
        if (!cursorSet)
            game.setCursor(SystemCursor.Default);
    }
    
    override void onResize(int width, int height)
    {
        if (!initialized)
            return;
        
        resizeThumbs(game.drawableWidth, game.drawableHeight);
    }
    
    void resizeThumbs(int width, int height)
    {
        if (!initialized)
            return;
        
        frame.visible = false;
        
        carThumbHeight = min(180, cast(uint)(cast(float)height / 4.0f));
        carThumbWidth = min(360, cast(uint)(cast(float)carThumbHeight * carThumbAspectRatio));
        float leftOffsetX = 260.0f;
        float posX = leftOffsetX;
        float posY = 10.0f;
        float gap = 10.0f;
        foreach(i, thumb; carThumbs)
        {
            thumb.scaling = Vector3f(carThumbWidth, carThumbHeight, 1.0f);
            thumb.position = Vector3f(posX, posY, 0.0f);
            
            if (selectedCarIndex == i)
            {
                frame.scaling = thumb.scaling;
                frame.position = thumb.position;
                frame.visible = true;
            }
            
            posX += carThumbWidth + gap;
            if (posX > width - carThumbWidth)
            {
                posX = leftOffsetX;
                posY += carThumbHeight + gap;
            }
        }
    }
    
    override void onKeyDown(int key)
    {
        if (key == KEY_F4)
        {
            game.updateRenderers(Time(0.0, 0.0));
            game.takeScreenshot("screenshots/screenshot");
        }
    }
    
    override void onKeyUp(int key) { }
    
    override void onMouseButtonDown(int button)
    {
        foreach(i, thumb; carThumbs)
        {
            if (eventManager.mouseX >= thumb.position.x && eventManager.mouseX < thumb.position.x + thumb.scaling.x &&
                eventManager.mouseY >= thumb.position.y && eventManager.mouseY < thumb.position.y + thumb.scaling.y)
            {
                selectedCarIndex = i;
                selectedCarFilename = carConfigs[selectedCarIndex];
                frame.scaling = thumb.scaling;
                frame.position = thumb.position;
                frame.visible = true;
                break;
            }
        }
    }
    
    override void onMouseButtonUp(int button) { }
}
