/*
Copyright (c) 2021-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module game;

import dlib.core.memory;

import dagon.core.time;
import dagon.game.game;
import dagon.resource.asset;
import dagon.resource.scene;
import dagon.resource.texture;
import dagon.ext.imgui;

import soloud;

import race;
import menu;
import ui;

class ChillwaveDriveGame: Game
{
    Soloud audio;
    ImGui imgui;
    
    AssetManager assetManager;
    TextureAsset splash;
    TextureAsset mainMenuBackground;
    
    // TODO: make a separate Audio class
    float sfxVolume = 0.5f;
    float musicVolume = 0.5f;
    
    Wav sfxClose;
    Wav sfxClick;
    Wav sfxPopup;
    Wav sfxSwitch;
    
    string defaultCar = "data/cars/cc_050/cc_050.json";
    
    this(uint w, uint h, bool fullscreen, string title, string[] args)
    {
        super(w, h, fullscreen, title, args);
        
        if (args.length > 1)
            defaultCar = args[1];
        
        assetManager = New!AssetManager(eventManager, vfs, this);
        assetManager.application = this;
        
        audio = Soloud.create();
        audio.init(Soloud.CLIP_ROUNDOFF | Soloud.LEFT_HANDED_3D);
        
        splash = loadTexture("data/ui/splash_screen.webp");
        mainMenuBackground = loadTexture("data/ui/main_menu_background.webp");
        
        auto mainMenuScene = New!MainMenuScene(this);
        scenes["MainMenu"] = mainMenuScene;
        currentScene = mainMenuScene;
        
        imgui = New!ImGui(this);
        eventManager.onProcessEvent = &imgui.onProcessEvent;
        
        sfxClose = Wav.create();
        sfxClose.load("data/sounds/close.wav");
        
        sfxClick = Wav.create();
        sfxClick.load("data/sounds/click.wav");
        
        sfxPopup = Wav.create();
        sfxPopup.load("data/sounds/popup.wav");
        
        sfxSwitch = Wav.create();
        sfxSwitch.load("data/sounds/switch.wav");
    }
    
    TextureAsset loadTexture(string filename)
    {
        auto asset = New!TextureAsset(assetManager);
        asset.threadSafePartLoaded = assetManager.loadAssetThreadSafePart(asset, filename);
        if (asset.threadSafePartLoaded)
            asset.threadUnsafePartLoaded = asset.loadThreadUnsafePart();
        return asset;
    }
    
    override void setCurrentScene(Scene scene, bool releaseCurrent = false)
    {
        super.setCurrentScene(scene, releaseCurrent);
    }
    
    override void setCurrentScene(string name, bool releaseCurrent = false)
    {
        super.setCurrentScene(name, releaseCurrent);
        
        if (name == "MainMenu")
        {
            imgui.active = true;
        }
    }
    
    override void onUpdate(Time t)
    {
        super.onUpdate(t);
        imgui.update(t);
    }
    
    override void onRender()
    {
        super.onRender();
        imgui.render();
    }
    
    void updateRenderers(Time t)
    {
        renderer.update(t);
        postProcessingRenderer.update(t);
        presentRenderer.update(t);
        hudRenderer.update(t);
        postProcessingRenderer.inputBuffer = renderer.outputBuffer;
    }
}
