/*
Copyright (c) 2021-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module race;

import std.stdio;
import std.conv;
import std.meta;
import std.math;
import std.random;
import std.algorithm.sorting: sort;

import dlib.core.memory;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.quaternion;
import dlib.math.transformation;
import dlib.math.utils;
import dlib.math.interpolation;
import dlib.image.color;
import dlib.text.str;

import dagon.core.keycodes;
import dagon.core.time;
import dagon.graphics.entity;
import dagon.graphics.components;
import dagon.graphics.material;
import dagon.graphics.texture;
import dagon.graphics.shapes;
import dagon.graphics.camera;
import dagon.graphics.light;
import dagon.graphics.particles;
import dagon.graphics.texproc;
import dagon.resource.scene;
import dagon.resource.texture;
import dagon.resource.font;
import dagon.resource.gltf;
import dagon.game.loadingscreen;
import dagon.ui.textline;
import dagon.ui.widget;
import dagon.ext.newton;
import dagon.ext.imgui;

import soloud;

import game;
import vehicle;
import wheel;
import car;
import racingview;
import ai;
import weather;
import track;
import ui;

class RaceScene: Scene
{
    FontAsset aFontDroidSans14;
    
    ChillwaveDriveGame game;
    Soloud audio;
    
    LoadingScreen loadingScreen;
    
    GLTFAsset aTrack;
    
    Camera camera;
    RacingViewComponent vehicleView;
    
    NewtonPhysicsWorld physicsWorld;
    
    TextureAsset aRain;
    
    CarAsset mclaren;
    
    Car car;
    Car car2;
    Car car3;
    
    TextureAsset aCarShadow;
    TextureAsset aTexParticleDust;
    
    TextureAsset aEnvmap;
    
    TextureAsset aTachometerArrow;
    TextureAsset aTachometer;
    
    Light sun;
    
    ParticleSystem particleSystem;
    Emitter emitterLeft;
    Emitter emitterRight;
    
    bool headlightsPressed = false;
    
    bool headlightsOn = true;
    float headlightsEnergy = 10.0f;
    Material headlightsMaterial;
    Light light1, light2, light1_vol, light2_vol;
    
    Color4f ambientClearSkyDay = Color4f(0.4f, 0.4f, 0.7f, 1.0f);
    Color4f ambientClearSkySunset = Color4f(0.6f, 0.4f, 0.7f, 1.0f);
    Color4f ambientClearSkyNight = Color4f(0.3f, 0.3f, 0.6f, 1.0f);
    
    Color4f ambientCloudySkyDay = Color4f(0.4f, 0.4f, 0.5f, 1.0f);
    Color4f ambientCloudySkySunset = Color4f(0.6f, 0.3f, 0.3f, 1.0f);
    Color4f ambientCloudySkyNight = Color4f(0.4f, 0.4f, 0.7f, 1.0f);
    
    Color4f fogDay = Color4f(0.4f, 0.5f, 0.7f, 1.0f);
    Color4f fogSunset = Color4f(0.6f, 0.4f, 0.7f, 1.0f);
    Color4f fogNight = Color4f(0.0f, 0.0f, 0.0f, 1.0f);
    
    UIWidget gameHUD;
    UIWidget tachometer;
    UIWidget tachometerArrowPivot;
    UIWidget tachometerArrow;
    
    UIWidget overlay;

    WavStream music;
    WavStream sfxAmbient;
    Wav sfxEngine1;
    Wav sfxEngine2;
    Wav sfxSteer;
    Wav sfxWheels;
    Wav sfxSqueal;
    Wav sfxSkid;
    Wav sfxSlip;
    Wav sfxPopping;
    Wav[2] sfxSuspension;
    Wav[2] sfxHit;
    Wav sfxCamera;
    
    int musicVoice;
    int engine1Voice;
    int engine2Voice;
    int steerVoice;
    int wheelsVoice;
    int squealVoice;
    int skidVoice;
    int poppingVoice;
    int hitVoice;
    int suspVoice;
    int slipVoice;
    
    float musicVolume = 0.5f;
    float sfxVolume = 0.5f;
    
    int lastMouseX, lastMouseY;
    
    float suspensionMaxLength = 0.3f;
    float suspensionStiffness = 100.0f;
    float suspensionDamping = 10.0f;
    
    Entity eText;
    Entity eText2;
    
    TextLine text;
    TextLine textShadow;
    
    Track track;
    
    Vector3f[] waypoints = 
    [
        Vector3f(0.0, 0.0, -0.0),
        Vector3f(20.0, 0.0, -0.0),
        Vector3f(40.0, 0.0, -0.0),
        Vector3f(60.0, 0.0, -0.0),
        Vector3f(80.0, 0.0, -0.0),
        Vector3f(100.0, 0.0, -0.0),
        Vector3f(120.0, 0.0, -0.0),
        Vector3f(140.0, 0.0, -0.0),
        Vector3f(160.0, 0.0, -0.0),
        Vector3f(180.0, 0.0, -0.0),
        Vector3f(200.0, 0.0, 10.0),
        Vector3f(220.0, 0.0, 20.0),
        Vector3f(240.0, 0.0, 30.0),
        Vector3f(260.0, 0.0, 40.0),
        Vector3f(270.0, 0.0, 60.0),
        Vector3f(270.0, 0.0, 80.0),
        Vector3f(270.0, 0.0, 100.0),
        Vector3f(270.0, 0.0, 120.0),
        Vector3f(270.0, 0.0, 140.0),
        Vector3f(260.0, 0.0, 160.0),
        Vector3f(240.0, 0.0, 180.0),
        Vector3f(220.0, 0.0, 180.0),
        Vector3f(200.0, 0.0, 177.0),
        Vector3f(175.0, 0.0, 192.0),
        Vector3f(170.0, 0.0, 220.0),
        Vector3f(170.0, 0.0, 240.0),
        Vector3f(170.0, 0.0, 260.0),
        Vector3f(160.0, 0.0, 280.0),
        Vector3f(144.0, 0.0, 294.0),
        Vector3f(124.0, 0.0, 302.0),
        Vector3f(100.0, 0.0, 302.0),
        Vector3f(76.0, 0.0, 294.0),
        Vector3f(60.0, 0.0, 272.0),
        Vector3f(56.0, 0.0, 248.0),
        Vector3f(56.0, 0.0, 220.0),
        Vector3f(56.0, 0.0, 200.0),
        Vector3f(56.0, 0.0, 180.0),
        Vector3f(54.0, 0.0, 160.0),
        Vector3f(48.0, 0.0, 140.0),
        Vector3f(36.0, 0.0, 120.0),
        Vector3f(20.0, 0.0, 102.0),
        Vector3f(0.0, 1.0, 86.0),
        Vector3f(-22.0, 2.0, 78.0),
        Vector3f(-46.0, 3.0, 74.0),
        Vector3f(-66.0, 4.0, 74.0),
        Vector3f(-84.0, 4.0, 74.0),
        Vector3f(-104.0, 4.0, 74.0),
        Vector3f(-122.0, 3.0, 74.0),
        Vector3f(-144.0, 2.0, 76.0),
        Vector3f(-164.0, 1.0, 86.0),
        Vector3f(-180.0, 0.0, 104.0),
        Vector3f(-194.0, 0.0, 128.0),
        Vector3f(-198.0, 0.0, 154.0),
        Vector3f(-198.0, 0.0, 180.0),
        Vector3f(-198.0, 0.0, 200.0),
        Vector3f(-198.0, 0.0, 220.0),
        Vector3f(-200.0, 0.0, 240.0),
        Vector3f(-206.0, 0.0, 262.0),
        Vector3f(-222.0, 0.0, 284.0),
        Vector3f(-240.0, 0.0, 302.0),
        Vector3f(-266.0, 0.0, 316.0),
        Vector3f(-290.0, 0.0, 322.0),
        Vector3f(-316.0, 0.0, 328.0),
        Vector3f(-340.0, 0.0, 328.0),
        Vector3f(-360.0, 0.0, 328.0),
        Vector3f(-380.0, 0.0, 328.0),
        Vector3f(-400.0, 0.0, 326.0),
        Vector3f(-426.0, 0.0, 318.0),
        Vector3f(-446.0, 0.0, 308.0),
        Vector3f(-464.0, 0.0, 288.0),
        Vector3f(-464.0, 0.0, 262.0),
        Vector3f(-458.0, 0.0, 240.0),
        Vector3f(-440.0, 0.0, 222.0),
        Vector3f(-418.0, 0.0, 210.0),
        Vector3f(-388.0, 0.0, 204.0),
        Vector3f(-364.0, 0.0, 190.0),
        Vector3f(-344.0, 0.0, 164.0),
        Vector3f(-326.0, 0.0, 128.0),
        Vector3f(-312.0, 0.0, 92.0),
        Vector3f(-288.0, 0.0, 66.0),
        Vector3f(-254.0, 0.0, 42.0),
        Vector3f(-212.0, 0.0, 22.0),
        Vector3f(-178.0, 0.0, 14.0),
        Vector3f(-136.0, 0.0, 4.0),
        Vector3f(-102.0, 0.0, -0.0),
        Vector3f(-80.0, 0.0, -0.0),
        Vector3f(-60.0, 0.0, -0.0),
        Vector3f(-40.0, 0.0, -0.0),
        Vector3f(-20.0, 0.0, -0.0),
        Vector3f(0.0, 0.0, -0.0)
    ];
    
    Entity lookaheadMarker;
    
    Car[] participants;
    
    Autopilot autopilot;
    Autopilot autopilot2;
    Autopilot autopilot3;
    
    bool raceStarted = false;
    
    Entity eSky;
    
    Rain rain;
    Entity eRain;
    float skyCleanupTimer = 0.0f;
    int skyCleanupMode = 0;
    float nextCleanupDuration = 10.0f;
    
    bool rumbleEnabled = true;

    this(ChillwaveDriveGame game)
    {
        super(game);
        this.game = game;
        this.audio = game.audio;
        
        auto splashTextureAsset = addTextureAsset("data/ui/splash_screen.jpg", true);
        
        loadingScreen = New!LoadingScreen(game, this);
        loadingScreen.backgroundTexture = splashTextureAsset.texture;
        loadingScreen.progressbarCentered = false;
    }
    
    ~this()
    {
        mclaren.free();
        Delete(participants);
    }
    
    void loadCarConfig(string filename, CarAsset* carAsset)
    {
        carAsset.aCar = New!JSONAsset(assetManager);
        assetManager.preloadExternalAsset(carAsset.aCar, filename);
        
        string chassisFilename;
        auto root = carAsset.aCar.doc.root.asObject;
        if ("chassis" in root)
        {
            auto chassis = root["chassis"];
            chassisFilename = jsonPropString(chassis, "model", "");
        }
        
        if (chassisFilename.length)
            carAsset.aChassis = addGLTFAsset(chassisFilename);
        
        if ("windows" in root)
        {
            auto windows = root["windows"];
            string windowsFilename = jsonPropString(windows, "model", "");
            if (windowsFilename.length)
                carAsset.aWindows = addGLTFAsset(windowsFilename);
        }
        
        if ("wheels" in root)
        {
            auto wheels = root["wheels"].asArray;
            foreach(wheel; wheels)
            {
                string wheelFilename = jsonPropString(wheel, "model", "");
                auto aWheel = addGLTFAsset(wheelFilename);
                carAsset.aWheels.append(aWheel);
            }
        }
    }

    override void beforeLoad()
    {
        aFontDroidSans14 = addFontAsset("data/font/DroidSans.ttf", 14);
        
        aEnvmap = addTextureAsset("data/envmaps/shudu_lake_4k.hdr");
        
        aRain = addTextureAsset("data/particles/rain.png");
        
        // Track
        aTrack = addGLTFAsset("data/track/racetrack.gltf");
        
        // Cars
        loadCarConfig("data/cars/mclaren_gt/mclaren_gt.json", &mclaren);
        //loadCarConfig("data/cars/aston_martin_one77/aston_martin_one77.json", &astonMartin);
        
        aCarShadow = addTextureAsset("data/misc/car_shadow.png");
        
        aTexParticleDust = addTextureAsset("data/particles/dust.png");
        
        aTachometer = addTextureAsset("data/ui/tachometer.png");
        aTachometerArrow = addTextureAsset("data/ui/tachometer_arrow.png");
        
        // Sounds
        sfxEngine1 = Wav.create();
        sfxEngine1.load("data/sounds/engine.wav");
        sfxEngine1.set3dDistanceDelay(true);
        
        sfxEngine2 = Wav.create();
        sfxEngine2.load("data/sounds/engine2.wav");
        sfxEngine2.set3dDistanceDelay(true);
        
        sfxSteer = Wav.create();
        sfxSteer.load("data/sounds/steer.wav");
        sfxSteer.set3dDistanceDelay(true);
        
        sfxWheels = Wav.create();
        sfxWheels.load("data/sounds/wheels.wav");
        sfxWheels.set3dDistanceDelay(true);
        
        sfxSqueal = Wav.create();
        sfxSqueal.load("data/sounds/squeal.wav");
        sfxSqueal.set3dDistanceDelay(true);
        
        sfxSkid = Wav.create();
        sfxSkid.load("data/sounds/skid.wav");
        sfxSkid.set3dDistanceDelay(true);
        
        sfxSlip = Wav.create();
        sfxSlip.load("data/sounds/gravel.mp3");
        sfxSlip.set3dDistanceDelay(true);
        
        sfxSuspension[0] = Wav.create();
        sfxSuspension[0].load("data/sounds/suspension1.wav");
        sfxSuspension[0].set3dDistanceDelay(true);
        
        sfxSuspension[1] = Wav.create();
        sfxSuspension[1].load("data/sounds/suspension2.wav");
        sfxSuspension[1].set3dDistanceDelay(true);
        
        sfxPopping = Wav.create();
        sfxPopping.load("data/sounds/muffler_pop.mp3");
        sfxPopping.set3dDistanceDelay(true);
        
        sfxHit[0] = Wav.create();
        sfxHit[0].load("data/sounds/hit1.wav");
        sfxHit[0].set3dDistanceDelay(true);
        
        sfxHit[1] = Wav.create();
        sfxHit[1].load("data/sounds/hit2.wav");
        sfxHit[1].set3dDistanceDelay(true);
        
        sfxCamera = Wav.create();
        sfxCamera.load("data/sounds/camera.wav");
        sfxCamera.set3dDistanceDelay(true);
        
        sfxAmbient = WavStream.create();
        sfxAmbient.load("data/sounds/rain.mp3");
        
        music = WavStream.create();
        music.load("data/music/Machine Code.mp3");
    }
    
    override void onLoad(Time t, float progress)
    {
        loadingScreen.progressbar.position = Vector3f(
            (game.drawableWidth - loadingScreen.progressbarWidth) * 0.5f,
            game.drawableHeight - 40.0f, 0);
        loadingScreen.update(t, progress);
        loadingScreen.render();
    }

    override void afterLoad()
    {
        environment.backgroundColor = Color4f(0.1f, 0.05f, 0.1f, 1.0f);
        environment.fogColor = environment.backgroundColor;
        environment.fogStart = 0.0f;
        environment.fogEnd = 1000.0f;
        
        physicsWorld = New!NewtonPhysicsWorld(eventManager, assetManager);
        version(Windows) physicsWorld.loadPlugins(".");
        
        sun = addLight(LightType.Sun);
        //sun.color = Color4f(1.0f, 0.95f, 0.9f, 1.0f);
        sun.color = Color4f(1.0f, 0.9f, 0.8f, 1.0f);
        sun.shadowEnabled = true;
        sun.energy = 0.0f;
        sun.turn(-35.0f); //0.0f
        sun.pitch(-15.0f); //-30.0f
        sun.scatteringEnabled = true;
        sun.scattering = 0.3f;
        sun.mediumDensity = 0.3f;
        sun.scatteringUseShadow = false;
        sun.scatteringMaxRandomStepOffset = 0.5f;
        environment.sun = sun;
        
        Texture cubemap = generateCubemap(1024, aEnvmap.texture, assetManager);
        Texture prefilteredCubemap = prefilterCubemap(1024, cubemap, assetManager);
        
        environment.ambientMap = prefilteredCubemap;
        environment.ambientBRDF = game.deferredRenderer.brdf;
        environment.ambientEnergy = 0.05f;
        
        // Track
        aTrack.markTransparentEntities();
        useEntity(aTrack.rootEntity);
        foreach(node; aTrack.nodes)
        {
            useEntity(node.entity);
            node.entity.dynamic = false;
        }
        
        auto eTrack = addEntity();
        auto trackShape = New!NewtonMeshShape(aTrack, physicsWorld);
        eTrack.makeStaticBody(physicsWorld, trackShape);
        
        track = New!Track(this);
        track.waypoints = waypoints;
        GroundMaterial gm;
        foreach(i, mat; aTrack.materials)
        {
            mat.useCulling = false;
            if (i == 1) // grass
            {
                gm.grip = 0.9f;
                gm.rollingResistanceC0 = 0.008f;
                gm.rollingResistanceC1 = 0.002f;
                gm.rollingResistanceC2 = 0.0008f;
            }
            else
            {
                gm.grip = 1.0f;
                gm.rollingResistanceC0 = 0.001f;
                gm.rollingResistanceC1 = 0.0005f;
                gm.rollingResistanceC2 = 0.000f;
            }
            track.addMaterial(gm);
        }
        
        // Waypoints visuals
        /*
        auto sphere = New!ShapeSphere(0.5f, assetManager);
        auto mSphere = addMaterial();
        mSphere.baseColorFactor = Color4f(1.0f, 0.0f, 0.0f, 1.0f);
        mSphere.blendMode = Transparent;
        mSphere.opacity = 0.5f;
        foreach(wp; waypoints)
        {
            auto wpSphere = addEntity();
            wpSphere.drawable = sphere;
            wpSphere.material = mSphere;
            wpSphere.position = wp + Vector3f(0.0f, 1.0f, 0.0f);
        }
        
        lookaheadMarker = addEntity();
        lookaheadMarker.drawable = sphere;
        lookaheadMarker.material = addMaterial();
        lookaheadMarker.material.baseColorFactor = Color4f(1.0f, 1.0f, 0.0f, 1.0f);
        lookaheadMarker.position = waypoints[1] + Vector3f(0.0f, 1.0f, 0.0f);
        */
        
        participants = New!(Car[])(3);
        
        // User-controlled car
        mclaren.shadowTexture = aCarShadow.texture;
        car = New!Car(this, physicsWorld, &mclaren, Vector3f(0.0f, 0.8f, 4.0f), 90.0f, this);
        car.isPlayer = true;
        car.name = String("Player");
        car.vehicle.track = track;
        car.carPaintMaterial.baseColorFactor = Color4f(1.0f, 0.5f, 0.0f, 1.0f);
        car.vehicle.addAntiRollBar(car.vehicle.wheels[0], car.vehicle.wheels[1], 2000.0f);
        car.vehicle.addAntiRollBar(car.vehicle.wheels[2], car.vehicle.wheels[3], 2000.0f);
        car.vehicle.arcadeSteering = true;
        autopilot = New!Autopilot(car, this);
        autopilot.track = track;
        autopilot.maxSpeed = 45.0f;
        autopilot.maxLateralAcceleration = 15.0f;
        autopilot.maxSegmentsToSearch = 10;
        autopilot.steeringForce = 20.0f;
        autopilot.active = false;
        participants[0] = car;
        
        // Opponent cars
        car2 = New!Car(this, physicsWorld, &mclaren, Vector3f(0.0f, 0.8f, -4.0f), 90.0f, this);
        car2.name = String("AI 1");
        car2.vehicle.track = track;
        car2.carPaintMaterial.baseColorFactor = Color4f(0.0f, 0.5f, 1.0f, 1.0f);
        car2.vehicle.addAntiRollBar(car2.vehicle.wheels[0], car2.vehicle.wheels[1], 2000.0f);
        car2.vehicle.addAntiRollBar(car2.vehicle.wheels[2], car2.vehicle.wheels[3], 2000.0f);
        car2.vehicle.arcadeSteering = false;
        autopilot2 = New!Autopilot(car2, this);
        autopilot2.track = track;
        autopilot2.maxSpeed = 45.0f;
        autopilot2.maxLateralAcceleration = 15.0f;
        autopilot2.maxSegmentsToSearch = 10;
        autopilot2.steeringForce = 20.0f;
        participants[1] = car2;
        
        car3 = New!Car(this, physicsWorld, &mclaren, Vector3f(15.0f, 0.8f, 0.0f), 90.0f, this);
        car3.name = String("AI 2");
        car3.vehicle.track = track;
        car3.carPaintMaterial.baseColorFactor = Color4f(1.0f, 0.1f, 0.1f, 1.0f);
        car3.vehicle.addAntiRollBar(car3.vehicle.wheels[0], car3.vehicle.wheels[1], 2000.0f);
        car3.vehicle.addAntiRollBar(car3.vehicle.wheels[2], car3.vehicle.wheels[3], 2000.0f);
        car3.vehicle.arcadeSteering = false;
        autopilot3 = New!Autopilot(car3, this);
        autopilot3.track = track;
        autopilot3.maxSpeed = 45.0f;
        autopilot3.maxLateralAcceleration = 15.0f;
        autopilot3.maxSegmentsToSearch = 10;
        autopilot3.steeringForce = 20.0f;
        participants[2] = car3;
        
        auto eParticles = addEntity();
        particleSystem = New!ParticleSystem(eventManager, eParticles);
        
        // Dust particle systems
        auto mParticlesDust = addMaterial();
        mParticlesDust.baseColorTexture = aTexParticleDust.texture;
        mParticlesDust.blendMode = Transparent;
        mParticlesDust.shadeless = true;
        mParticlesDust.depthWrite = false;
        mParticlesDust.sun = sun;
        mParticlesDust.opacity = 0.2f;
        mParticlesDust.useShadows = true;

        auto eParticlesRight = addEntity(car.eCar);
        emitterRight = New!Emitter(eParticlesRight, particleSystem, 30);
        eParticlesRight.position = Vector3f(-0.9f, 0.0f, -0.5f);
        emitterRight.minLifetime = 1.0f;
        emitterRight.maxLifetime = 3.0f;
        emitterRight.minSize = 0.5f;
        emitterRight.maxSize = 1.0f;
        emitterRight.minInitialSpeed = 0.2f;
        emitterRight.maxInitialSpeed = 0.2f;
        emitterRight.scaleStep = Vector2f(2, 2);
        emitterRight.material = mParticlesDust;
        emitterRight.emitting = false;
        eParticlesRight.castShadow = false;
        eParticlesRight.visible = true;

        auto eParticlesLeft = addEntity(car.eCar);
        emitterLeft = New!Emitter(eParticlesLeft, particleSystem, 30);
        eParticlesLeft.position = Vector3f(0.9f, 0.0f, -0.5f);
        emitterLeft.minLifetime = 1.0f;
        emitterLeft.maxLifetime = 3.0f;
        emitterLeft.minSize = 0.5f;
        emitterLeft.maxSize = 1.0f;
        emitterLeft.minInitialSpeed = 0.2f;
        emitterLeft.maxInitialSpeed = 0.2f;
        emitterLeft.scaleStep = Vector2f(2, 2);
        emitterLeft.material = mParticlesDust;
        emitterLeft.emitting = false;
        eParticlesLeft.castShadow = false;
        eParticlesLeft.visible = true;
        
        rain = New!Rain(assetManager);
        rain.size = Vector3f(4.0f, 4.0f, 4.0f);
        rain.velocity = Vector3f(0.0f, -30.0f, 0.0f);
        eRain = addEntity();
        eRain.drawable = rain;
        eRain.material = addMaterial();
        eRain.material.baseColorTexture = aRain.texture;
        eRain.material.blendMode = Transparent;
        eRain.material.opacity = 0.01f;
        eRain.material.shadeless = true;
        eRain.material.emissionEnergy = 1.0f;
        eRain.material.emissionFactor = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        eRain.material.useCulling = false;
        eRain.material.depthWrite = false;
        eRain.gbufferMask = 0.0f;
        
        camera = addCamera();
        camera.fov = 42.0f;
        game.renderer.activeCamera = camera;
        
        eSky = addEntity();
        auto psync = New!PositionSync(eventManager, eSky, camera);
        eSky.drawable = New!ShapeBox(Vector3f(1.0f, 1.0f, 1.0f), assetManager);
        eSky.scaling = Vector3f(100.0f, 100.0f, 100.0f);
        eSky.layer = EntityLayer.Background;
        eSky.material = New!Material(assetManager);
        eSky.material.depthWrite = false;
        eSky.material.useCulling = false;
        eSky.material.baseColorTexture = prefilteredCubemap;
        eSky.material.linearColor = true;
        eSky.material.emissionEnergy = environment.ambientEnergy;
        eSky.gbufferMask = 0.0f;
        
        vehicleView = New!RacingViewComponent(eventManager, camera, car.eCar);
        vehicleView.active = false;
        
        auto ambientVoice = audio.play(sfxAmbient);
        audio.setLooping(ambientVoice, true);
        audio.setVolume(ambientVoice, 2.0f * sfxVolume);
        
        engine1Voice = audio.play3d(sfxEngine1, car.position.x, car.position.y, car.position.z);
        audio.setLooping(engine1Voice, true);
        audio.set3dSourceMinMaxDistance(engine1Voice, 1.0f, 50.0f);
        audio.setVolume(engine1Voice, sfxVolume);
        
        engine2Voice = audio.play3d(sfxEngine2, car.position.x, car.position.y, car.position.z);
        audio.setLooping(engine2Voice, true);
        audio.set3dSourceMinMaxDistance(engine2Voice, 1.0f, 50.0f);
        audio.setVolume(engine2Voice, 0.0f);
        
        steerVoice = audio.play3d(sfxSteer, car.position.x, car.position.y, car.position.z);
        audio.setLooping(steerVoice, true);
        audio.set3dSourceMinMaxDistance(steerVoice, 1.0f, 50.0f);
        audio.setVolume(steerVoice, 0.0f);
        
        wheelsVoice = audio.play3d(sfxWheels, car.position.x, car.position.y, car.position.z);
        audio.setLooping(wheelsVoice, true);
        audio.set3dSourceMinMaxDistance(wheelsVoice, 1.0f, 50.0f);
        audio.setVolume(wheelsVoice, 0.0f);
        
        squealVoice = audio.play3d(sfxSqueal, car.position.x, car.position.y, car.position.z);
        audio.setVolume(squealVoice, 0.0f);
        audio.setLooping(squealVoice, true);
        
        skidVoice = audio.play3d(sfxSkid, car.position.x, car.position.y, car.position.z);
        audio.setVolume(skidVoice, 0.0f);
        audio.setLooping(skidVoice, true);
        
        slipVoice = audio.play3d(sfxSlip, car.position.x, car.position.y, car.position.z);
        audio.setVolume(slipVoice, 0.0f);
        audio.setLooping(slipVoice, true);
        
        poppingVoice = audio.play3d(sfxPopping, car.position.x, car.position.y, car.position.z);
        audio.setVolume(poppingVoice, 0.0f);
        audio.setLooping(poppingVoice, true);
        audio.set3dSourceMinMaxDistance(poppingVoice, 1.0f, 50.0f);
        
        audio.update3dAudio();
        
        eText = addEntityHUD();
        eText.position = Vector3f(16.0f, 30.0f, 0.0f);
        eText.visible = false;
        
        auto eTextShadow = addEntityHUD(eText);
        textShadow = New!TextLine(aFontDroidSans14.font, "0", assetManager);
        textShadow.color = Color4f(0.0f, 0.0f, 0.0f, 0.5f);
        eTextShadow.drawable = textShadow;
        eTextShadow.position = Vector3f(1.0f, 1.0f, 0.0f);
        eTextShadow.visible = false;
        
        auto eTextFg = addEntityHUD(eText);
        text = New!TextLine(aFontDroidSans14.font, "0", assetManager);
        text.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        eTextFg.drawable = text;
        eTextFg.visible = false;
        
        eText2 = addEntityHUD();
        eText2.position = Vector3f(16.0f, 30.0f, 0.0f);
        
        string hintStr = "Press Enter/Start to start the race. Press Escape to customize your car";
        
        auto text2Shadow = New!TextLine(aFontDroidSans14.font, hintStr, assetManager);
        text2Shadow.color = Color4f(0.0f, 0.0f, 0.0f, 0.5f);
        auto eText2Shadow = addEntityHUD(eText2);
        eText2Shadow.drawable = text2Shadow;
        eText2Shadow.position = Vector3f(1.0f, 1.0f, 0.0f);
        
        auto text2 = New!TextLine(aFontDroidSans14.font, hintStr, assetManager);
        text2.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        auto eText2Fg = addEntityHUD(eText2);
        eText2Fg.drawable = text2;
        
        gameHUD = addWidget!UIWidget();
        
        tachometerArrowPivot = addWidget!UIWidget(gameHUD);
        
        tachometerArrow = addWidget!UIWidget(tachometerArrowPivot);
        tachometerArrow.width = 256;
        tachometerArrow.height = 256;
        tachometerArrow.x = -128;
        tachometerArrow.y = -128;
        tachometerArrow.background.material.baseColorTexture = aTachometerArrow.texture;
        
        tachometer = addWidget!UIWidget(gameHUD);
        tachometer.width = 256;
        tachometer.height = 256;
        tachometer.background.material.baseColorTexture = aTachometer.texture;
        
        tachometer.x = game.drawableWidth - 48 - 256;
        tachometer.y = game.drawableHeight + 64 - 256;
        tachometerArrowPivot.x = tachometer.x + 128;
        tachometerArrowPivot.y = tachometer.y + 128;
        
        overlay = addWidget!UIWidget();
        overlay.backgroundFocusedColor = overlay.backgroundUnfocusedColor =
            Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        overlay.width = eventManager.windowWidth;
        overlay.height = eventManager.windowHeight;
        overlay.fitToParent = true;
        overlay.background.opacity = 0.0f;
        
        game.deferred.passLight.volumetricScatteringEnabled = false;
    }
    
    void restartRace()
    {
        car.restart();
        car2.restart();
        car3.restart();
        autopilot.reset();
        autopilot2.reset();
        autopilot3.reset();
        raceStarted = false;
        togglePause();
        eText.hide();
        eText2.show();
    }
    
    override void onKeyDown(int key)
    {
        // Global keys
        if (key == KEY_F4)
        {
            auto shotVoice = audio.play(sfxCamera);
            audio.setVolume(shotVoice, sfxVolume);
            application.takeScreenshot("screenshots/screenshot");
            overlay.background.opacity = 1.0f;
            overlay.background.fadeOut(0.25f);
        }
        else if (key == KEY_F5)
        {
            if (eText.visible)
                eText.hide();
            else
                eText.show();
            eText2.hide();
            
            auto clickVoice = audio.play(game.sfxClick);
            audio.setVolume(clickVoice, 2.0f * sfxVolume);
        }
        else if (key == KEY_M)
        {
            auto clickVoice = audio.play(game.sfxClick);
            audio.setVolume(clickVoice, 2.0f * sfxVolume);
            
            if (audio.isValidVoiceHandle(musicVoice))
            {
                audio.stop(musicVoice);
            }
            else
            {
                musicVoice = audio.play(music);
                audio.setLooping(musicVoice, true);
                audio.setVolume(musicVoice, musicVolume);
            }
        }
        else if (key == KEY_ESCAPE)
        {
            togglePause();
        }
        else if (paused)
            return;
        
        // In-game keys
        if (key == KEY_P)
        {
            autopilot.active = !autopilot.active;
            car.vehicle.arcadeSteering = !car.vehicle.arcadeSteering;
            auto clickVoice = audio.play(game.sfxClick);
            audio.setVolume(clickVoice, 2.0f * sfxVolume);
        }
        else if (key == KEY_RETURN)
        {
            if (!raceStarted)
            {
                startRace();
                auto clickVoice = audio.play(game.sfxClick);
                audio.setVolume(clickVoice, 2.0f * sfxVolume);
            }
        }
        else if (key == KEY_J)
        {
            car.vehicle.chassisBody.addForce(Vector3f(0.0f, 200000.0f, 0.0f));
            car.vehicle.chassisBody.addTorque(Vector3f(100000.0f, 0.0f, 0.0f));
        }
    }
    
    override void onControllerButtonDown(uint deviceIndex, int button)
    {
        if (button == GB_START)
        {
            if (!paused && !raceStarted)
            {
                startRace();
                auto clickVoice = audio.play(game.sfxClick);
                audio.setVolume(clickVoice, 2.0f * sfxVolume);
            }
            else
                togglePause();
        }
        else if (button == GB_BACK)
        {
            togglePause();
        }
    }
    
    void startRace()
    {
        if (!raceStarted)
        {
            raceStarted = true;
            eText2.hide();
            eText.show();
            
            autopilot.start();
            autopilot2.start();
            autopilot3.start();
            
            car.raceStarted = true;
            car2.raceStarted = true;
            car3.raceStarted = true;
        }
    }
    
    void togglePause()
    {
        vehicleView.active = false;
        if (!paused)
        {
            gameHUD.hide();
            game.ui.active = true;
            paused = true;
            audio.setPauseAll(true);
        }
        else
        {
            vehicleView.turnAngle = fmod(vehicleView.turnAngle, 2.0f * PI);
            vehicleView.pitchAngle = fmod(vehicleView.pitchAngle, 2.0f * PI);
            vehicleView.targetTurnAngle = fmod(vehicleView.targetTurnAngle, 2.0f * PI);
            vehicleView.targetPitchAngle = fmod(vehicleView.targetPitchAngle, 2.0f * PI);
            gameHUD.show();
            game.ui.active = false;
            paused = false;
            audio.setPauseAll(false);
            viewResetTime = 0.0f;
        }
        
        auto pauseVoice = audio.play(game.sfxClose);
        audio.setVolume(pauseVoice, 2.0f * sfxVolume);
    }
    
    override void onMouseButtonDown(int button)
    {
        if (game.ui.capturesMouse)
            return;
        
        if (button == MB_LEFT)
        {
            if (paused)
            {
                vehicleView.active = true;
                lastMouseX = eventManager.mouseX;
                lastMouseY = eventManager.mouseY;
                vehicleView.resetMouseInput();
            }
        }
    }
    
    override void onMouseButtonUp(int button)
    {
        if (game.ui.capturesMouse)
            return;
        
        if (button == MB_LEFT)
        {
            if (paused)
            {
                vehicleView.active = false;
                eventManager.setMouse(lastMouseX, lastMouseY);
            }
        }
    }
    
    float lastDirection = 0.0f;
    
    float accelerationPressed = false;
    float carEngineSoundSpeed = 1.0f;
    
    float triggerForward = 0.0f;
    float triggerBackward = 0.0f;
    
    override void onControllerAxisMotion(uint deviceIndex, int axis, float value)
    {
        if (paused)
            return;
        
        if (axis == GA_TRIGGERRIGHT)
        {
            triggerForward = value;
        }
        else if (axis == GA_TRIGGERLEFT)
        {
            triggerBackward = value;
        }
    }
    
    float joystickSteer = 0.0f;
    
    float steeringInputPrev = 0.0f;
    
    float gravelVolume = 0.0f;
    
    float speedKMH = 0.0f;
    
    override void onUpdate(Time t)
    {
        // Update AI
        autopilot.update(t);
        //lookaheadMarker.position = autopilot.targetPoint + Vector3f(0.0f, 1.0f, 0.0f);
        autopilot2.update(t);
        autopilot3.update(t);
        
        if (raceStarted && !autopilot.active)
        {
            // Car controls
            if (inputManager.getButton("forward"))
                car.vehicle.accelerate(1.0f, 2.0f * t.delta);
            else if (inputManager.getButton("back"))
                car.vehicle.accelerate(-1.0f, 2.0f * t.delta);
            else if (triggerForward > 0.0f)
                car.vehicle.accelerate(1.0f, triggerForward);
            else if (triggerBackward > 0.0f)
                car.vehicle.accelerate(-1.0f, triggerBackward);
            else
                car.vehicle.idle();
            
            carEngineSoundSpeed = lerp(1.0f, 1.5f, car.throttle);
            
            if (car.vehicle.arcadeSteering)
            {
                float axis = inputManager.getAxis("horizontal");
                car.vehicle.steer(-axis * 5.0f * t.delta);
            }
            else
                car.vehicle.manualSteer(joystickSteer);
        }
        
        // Headlights on/off
        if (inputManager.getButton("headlights"))
        {
            if (!headlightsPressed)
            {
                headlightsPressed = true;
                car.toggleHeadlights();
            }
        }
        else
            headlightsPressed = false;
        
        carEngineSoundSpeed = lerp(1.0f, 1.5f, car.throttle);
        
        car.update(t);
        car2.update(t);
        car3.update(t);
        
        const float velocityThreshold = 2.0f;
        const float angularThreshold = degtorad(30.0f);
        bool stopped = car.vehicle.chassisBody.velocity.length < velocityThreshold && car.vehicle.chassisBody.angularVelocity.length < angularThreshold;
        
        bool isOnGravel =
            car.vehicle.wheels[2].groundMaterialIndex == 1 ||
            car.vehicle.wheels[3].groundMaterialIndex == 1;
        
        // Rollover detection
        if (stopped && dot(car.eCar.up, Vector3f(0, 1, 0)) < 0.5f)
        {
            Vector3f newCarPos = car.vehicle.position + Vector3f(0.0f, 0.1f, 0.0f);
            Vector3f carDirection = car.eCar.direction;
            carDirection = Vector3f(carDirection.x, 0.0f, carDirection.z).normalized;
            float targetCarViewTurnAngle = -(atan2(carDirection.z, carDirection.x) - PI * 0.5f);
            Matrix4x4f newCarTransform =
                translationMatrix(newCarPos) *
                rotationQuaternion!float(Axis.y, targetCarViewTurnAngle).toMatrix4x4;
            car.vehicle.chassisBody.setTransformation(newCarTransform);
        }
        
        speedKMH = car.speedKMH();
        
        // Engine sound
        audio.set3dSourcePosition(engine1Voice, car.position.x, car.position.y, car.position.z);
        float newRpmFactor = clamp((car.rpm - 800.0f) / (6500.0f - 800.0f), 0.0f, 1.0f);
        rpmFactor += (newRpmFactor - rpmFactor) * 0.9f;
        float engineSoundSpeed = lerp(0.9f, 2.0f, rpmFactor); //1.8f;
        audio.setRelativePlaySpeed(engine1Voice, engineSoundSpeed);
        
        audio.set3dSourcePosition(engine2Voice, car.position.x, car.position.y, car.position.z);
        float engine2SoundSpeed = lerp(0.5f, 1.0f, rpmFactor);
        audio.setRelativePlaySpeed(engine2Voice, engineSoundSpeed);
        float engine2Volume = lerp(0.25f, 1.0f, rpmFactor * rpmFactor);
        audio.setVolume(engine2Voice, sfxVolume * engine2Volume);
        
        // Popping
        audio.setVolume(poppingVoice, sfxVolume * car.vehicle.popping * 3.0f);
        
        // Tire squeal sound
        float lateralSlip = car.lateralSlip;
        float longitudinalSlip = car.longitudinalSlip;
        float squealVolume = clamp(lateralSlip, 0.0f, 1.0f);
        if (car.brake) squealVolume = clamp((speedKMH - 30.0f) / 30.0f, 0.0f, 1.0f);
        float skidVolume = clamp(lateralSlip, 0.0f, 1.0f);
        float squealCoef = 1.0f;
        float slipSpeedFactor = clamp((speedKMH - 5.0f) / 5.0f, 0.0f, 1.0f);
        if (car.vehicle.wheels[0].groundMaterialIndex == 1 ||
            car.vehicle.wheels[1].groundMaterialIndex == 1 ||
            car.vehicle.wheels[2].groundMaterialIndex == 1 ||
            car.vehicle.wheels[3].groundMaterialIndex == 1)
        {
            squealCoef = 0.0f;
            audio.set3dSourcePosition(slipVoice, car.position.x, car.position.y, car.position.z);
            audio.setRelativePlaySpeed(slipVoice, slipSpeedFactor);
            if (gravelVolume < 1.0f)
                gravelVolume += 4.0f * t.delta;
            else
                gravelVolume = 1.0f;
        }
        else
        {
            if (gravelVolume > 0.0f)
                gravelVolume -= 4.0f * t.delta;
            else
                gravelVolume = 0.0f;
        }
        audio.setVolume(squealVoice, sfxVolume * squealVolume * 0.8f * squealCoef);
        audio.set3dSourcePosition(squealVoice, car.position.x, car.position.y, car.position.z);
        audio.setVolume(skidVoice, sfxVolume * 0.5f * skidVolume);
        audio.set3dSourcePosition(skidVoice, car.position.x, car.position.y, car.position.z);
        audio.setVolume(slipVoice, 0.5f * gravelVolume * slipSpeedFactor);
        
        // Wheels sound
        float wheelsVolume = 0.0f;
        if (!car.brake)
        {
            if (speedKMH <= 1.0f)
                wheelsVolume = clamp(speedKMH, 0.0f, 1.0f);
            else
                wheelsVolume = 1.0f - clamp((speedKMH - 1.0f) / 30.0f, 0.0f, 1.0f);
            wheelsVolume *= (1.0f - squealVolume);
        }
        float wheelsSoundSpeed = lerp(0.7f, 1.2f, clamp((speedKMH - 30.0f) / 30.0f, 0.0f, 1.0f));
        audio.setVolume(wheelsVoice, sfxVolume * wheelsVolume);
        audio.setRelativePlaySpeed(wheelsVoice, wheelsSoundSpeed);
        
        float steerVolume = cast(float)(abs(car.steeringInput - steeringInputPrev) > 0.01f) * 0.3f;
        steerVolume *= 1.0f - clamp((speedKMH - 1.0f) / 30.0f, 0.0f, 1.0f);
        audio.setVolume(steerVoice, sfxVolume * steerVolume);
        steeringInputPrev = car.steeringInput;
        
        foreach(w; car.vehicle.wheels)
        {
            float lengthDiff = abs(w.suspension.length - w.suspension.lengthPrev);
            if (lengthDiff > 0.01f)
            {
                if (!cast(bool)audio.isValidVoiceHandle(suspVoice))
                {
                    suspVoice = audio.play3d(sfxSuspension[uniform(0, $)], car.position.x, car.position.y, car.position.z);
                    audio.setVolume(suspVoice, 0.5f * sfxVolume);
                }
            }
        }
        
        // Feedback
        if (rumbleEnabled)
            updateGamepadRumble(car, speedKMH, lateralSlip, longitudinalSlip, isOnGravel, rpmFactor, t.delta);
        
        // Dust particles
        bool makingDust =
            lateralSlip > 0.0f || car.brake ||
            (isOnGravel && !car.vehicle.stopped);
        if (makingDust && car.vehicle.wheels[2].onGround) emitterLeft.emitting = true;
        else emitterLeft.emitting = false;
        if (makingDust && car.vehicle.wheels[3].onGround) emitterRight.emitting = true;
        else emitterRight.emitting = false;
        
        physicsWorld.update(t.delta);
        
        Vector3f camPos = camera.positionAbsolute;
        rain.spawnPosition = Vector3f(
            camPos.x,
            camPos.y + 2.0f,
            camPos.z
        );
        rain.update(t);
        
        if (skyCleanupMode == 0)
        {
            if (sun.energy < 0.5f)
                sun.energy += t.delta * 0.2f;
            else
                sun.energy = 0.5f;
            
            if (environment.ambientEnergy < 0.11f)
                environment.ambientEnergy += t.delta * 0.05f;
            else
                environment.ambientEnergy = 0.11f;
            
            if (skyCleanupTimer < nextCleanupDuration)
                skyCleanupTimer += t.delta;
            else
            {
                skyCleanupMode = 1;
                skyCleanupTimer = 0.0f;
                nextCleanupDuration = uniform(30.0f, 60.0f);
            }
        }
        else if (skyCleanupMode == 1)
        {
            if (sun.energy > 0.0f)
                sun.energy -= t.delta * 0.2f;
            else
                sun.energy = 0.0f;
            
            if (environment.ambientEnergy > 0.08f)
                environment.ambientEnergy -= t.delta * 0.05f;
            else
                environment.ambientEnergy = 0.08f;
            
            if (skyCleanupTimer < nextCleanupDuration)
                skyCleanupTimer += t.delta;
            else
            {
                skyCleanupMode = 0;
                skyCleanupTimer = 0.0f;
                nextCleanupDuration = uniform(5.0f, 15.0f);
            }
        }
        
        eSky.material.emissionEnergy = environment.ambientEnergy;
        
        // Feed camera data to 3D listener
        audio.set3dListenerPosition(camera.positionAbsolute.x, camera.positionAbsolute.y, camera.positionAbsolute.z);
        audio.set3dListenerAt(camera.directionAbsolute.x, camera.directionAbsolute.y, camera.directionAbsolute.z);
        audio.set3dListenerUp(camera.upAbsolute.x, camera.upAbsolute.y, camera.upAbsolute.z);
        audio.update3dAudio();
        
        updateLeaderboard();
        foreach (size_t i, ref car; participants)
        {
            car.racePosition = cast(uint)(i + 1);
        }
        
        updateHUD(t);
        
        if (abs(vehicleView.controllerAxisX) == 0.0f && abs(vehicleView.controllerAxisY) == 0.0f)
        {
            if (viewResetTime < 1.0f)
                viewResetTime += 0.25f * t.delta;
            else
                viewResetTime = 1.0f;
            vehicleView.targetTurnAngle = lerpAngle(vehicleView.targetTurnAngle, 0.0f, viewResetTime);
            vehicleView.targetPitchAngle = lerpAngle(vehicleView.targetPitchAngle, degtorad(15.0f), viewResetTime);
            vehicleView.targetDistance = lerp(vehicleView.targetDistance, vehicleView.minDistanceToTarget, viewResetTime);
        }
        else
        {
            viewResetTime = 0.0f;
        }
        
        eventManager.showCursor(false);
    }
    
    void updateHUD(Time t)
    {
        updateText(speedKMH);
        
        tachometer.x = game.drawableWidth - 48 - 256;
        tachometer.y = game.drawableHeight + 64 - 256;
        
        float tachometerTargetValue = lerp(-5.0f, 185.0f, clamp((car.rpm - 1000.0f) / 5000.0f, 0.0f, 1.0f));
        tachometerValue += (tachometerTargetValue - tachometerValue) * 10.0f * t.delta;
        tachometerArrowPivot.x = tachometer.x + 128;
        tachometerArrowPivot.y = tachometer.y + 128;
        tachometerArrowPivot.entity.rotation = rotationQuaternion!float(Axis.z, degtorad(tachometerValue));
    }
    
    void updateGamepadRumble(Car car, float speed, float lateralSlip, float longitudinalSlip, bool isOnGravel, float rpmFactor, double dt)
    {
        float lowFreq = 0.0f;
        float highFreq = 0.0f;
        
        if (car.vehicle.accelerating)
            highFreq = max2(highFreq, lerp(0.0f, 0.05f, rpmFactor));
        
        if (longitudinalSlip > 0.8f)
            highFreq = max2(highFreq, clamp(longitudinalSlip, 0.0f, 0.5f));
        
        if (lateralSlip > 0.5f)
            highFreq = max2(highFreq, 0.3f);

        if (isOnGravel && !car.vehicle.stopped)
            highFreq = max2(highFreq, 0.3f);

        if (speed > 15.0f)
        {
            foreach(wheel; car.vehicle.wheels)
            {
                float fDelta = abs(wheel.normalForce - wheel.normalForcePrev);
                if (fDelta > 1200.0f)
                    lowFreq = max2(lowFreq, 0.5f);
            }
        }

        uint low = cast(uint)(lowFreq * 65535);
        uint high = cast(uint)(highFreq * 65535);
        eventManager.gameControllerRumble(0, low, high, 0.04f);
    }
    
    float viewResetTime = 0.0f;
    
    override void onPauseUpdate(Time t)
    {
        updateHUD(t);
        
        ui.update(t);
        overlay.background.update(t);
        camera.update(t);
        
        eventManager.showCursor(!vehicleView.active);
    }
    
    void updateLeaderboard()
    {
        participants.sort!((a, b) {
            if (a.finished && b.finished)
                return a.raceTime < b.raceTime;
            if (a.laps != b.laps) 
                return a.laps > b.laps;
            if (a.trackSegmentIndex != b.trackSegmentIndex) 
                return a.trackSegmentIndex > b.trackSegmentIndex;
            return false; 
        });
    }
    
    float tachometerValue = 0.0f;
    
    float rpmFactor = 0.0f;
    
    char[1024] txt;
    void updateText(float speed)
    {
        uint fps = cast(int)(1.0 / eventManager.deltaTime);
        uint speedInt = cast(int)speed;
        uint lapMin = cast(uint)(car.lapTime / 60.0);
        uint lapSec = cast(uint)(car.lapTime) % 60;
        uint lapMsec = cast(uint)((car.lapTime - cast(uint)car.lapTime) * 1000.0);
        uint bestMin = cast(uint)(car.bestLapTime / 60.0);
        uint bestSec = cast(uint)(car.bestLapTime) % 60;
        uint bestMsec = cast(uint)((car.bestLapTime - cast(uint)car.bestLapTime) * 1000.0);
        //uint n = sprintf(txt.ptr, "Speed: %u km/h | gear: %u | RPM: %u | thr: %f | clt: %f", speedInt, car.gear + 1, cast(uint)car.rpm, car.throttle, car.clutch);
        uint n = sprintf(txt.ptr, "Lap: %u | Pos: %u | Lap time: %02u:%02u.%03u | Best time: %02u:%02u.%03u | Speed: %u km/h",
            min2(track.numLaps, car.laps + 1),
            car.racePosition,
            lapMin, lapSec, lapMsec,
            bestMin, bestSec, bestMsec,
            speedInt);
        string s = cast(string)txt[0..n];
        text.setText(s);
        textShadow.setText(s);
    }
}
