/*
Copyright (c) 2021-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module racingview;

import std.math;
import std.random;

import dagon;

float shortestAngleDelta(float from, float to)
{
    float delta = to - from;
    while (delta > PI)  delta -= 2.0f * PI;
    while (delta < -PI) delta += 2.0f * PI;
    return delta;
}

float lerpAngle(float current, float target, float t)
{
    float difference = target - current;
    float pi2 = 2.0f * PI;
    difference = fmod(difference, pi2);
    if (difference > PI)
        difference -= pi2;
    else if (difference < -PI)
        difference += pi2;
    return current + difference * t;
}

/// A third-person racing view component for the game camera.
class RacingViewComponent: EntityComponent
{
    Entity target;
    
    int oldMouseX;
    int oldMouseY;
    
    float targetTurnAngle = 0.0f;
    float turnAngle = 0.0f;
    
    float carViewTurnAngle = 0.0f;
    
    float targetPitchAngle = degtorad(15.0f);
    float pitchAngle = degtorad(15.0f);
    
    float minDistanceToTarget = 6.0f;
    float maxDistanceToTarget = 20.0f;
    
    float targetDistance;
    float smoothTargetDistance;
    
    bool active = true;
    bool mouseGrab = true;
    bool mouseActive = true;
    
    float mouseSensibility = 0.2f;
    float mouseZoomSensibility = 0.5f;
    
    float turnStiffness = 0.2f;
    float pitchStiffness = 0.2f;
    float zoomStiffness = 0.1f;

    this(EventManager em, Entity e, Entity target)
    {
        super(em, e);
        
        this.target = target;
        
        oldMouseX = eventManager.mouseX;
        oldMouseY = eventManager.mouseY;
        
        target.updateTransformationBottomUp();
        reset();
    }
    
    void reset()
    {
        targetDistance = minDistanceToTarget;
        smoothTargetDistance = targetDistance;
        
        turnAngle = targetTurnAngle;
        pitchAngle = clamp(targetPitchAngle, degtorad(10.0f), degtorad(40.0f));
        
        Vector3f carDirection = target.direction;
        carDirection = Vector3f(carDirection.x, 0.0f, carDirection.z).normalized;
        float targetCarViewTurnAngle = -(atan2(carDirection.z, carDirection.x) - PI * 0.5f);
        carViewTurnAngle = targetCarViewTurnAngle;
        
        Quaternionf carRotation =
            rotationQuaternion(Vector3f(0, 1, 0), carViewTurnAngle);

        Quaternionf mouseRotation =
            rotationQuaternion(Vector3f(0, 1, 0), turnAngle) *
            rotationQuaternion(Vector3f(1, 0, 0), pitchAngle);

        Quaternionf finalRotation = carRotation * mouseRotation;
        
        Vector3f offset = finalRotation.rotate(Vector3f(0.0f, 0.0f, 1.0f)).normalized;
        
        Vector3f cameraPosition = target.position + offset * -targetDistance;
        
        Vector3f viewFrom = cameraPosition;
        Vector3f viewTo = target.position + Vector3f(0, 1.0f, 0);
        Vector3f viewDir = (viewTo - viewFrom).normalized;
        Vector3f viewUp = Vector3f(0, 1, 0);
        Vector3f viewRight = cross(viewDir, viewUp);
        
        Matrix4x4f trans = lookAtMatrix(viewFrom, viewTo, Vector3f(0, 1, 0));
        
        entity.transformation = trans.inverse;
        entity.invTransformation = trans;
        
        entity.absoluteTransformation = entity.transformation;
        entity.invAbsoluteTransformation = entity.invTransformation;
        entity.prevAbsoluteTransformation = entity.prevTransformation;
    }
    
    void resetMouseInput()
    {
        eventManager.setMouseToCenter();
        oldMouseX = eventManager.mouseX;
        oldMouseY = eventManager.mouseY;
    }
    
    float controllerAxisX = 0.0f;
    float controllerAxisY = 0.0f;
    
    override void onControllerAxisMotion(uint deviceIndex, int axis, float value)
    {
        if (axis == GA_RIGHTX)
        {
            if (abs(value) > 0.1f)
                controllerAxisX = value;
            else
                controllerAxisX = 0.0f;
        }
        else if (axis == GA_RIGHTY)
        {
            if (abs(value) > 0.1f)
                controllerAxisY = value;
            else
                controllerAxisY = 0.0f;
        }
    }
    
    override void update(Time time)
    {
        processEvents();
        
        float turnDelta = 0.0f, pitchDelta = 0.0f;
        if (active & mouseGrab & mouseActive)
        {
            turnDelta = (eventManager.mouseX - oldMouseX) * mouseSensibility * time.delta;
            pitchDelta = -(eventManager.mouseY - oldMouseY) * mouseSensibility * time.delta;
            eventManager.setMouse(oldMouseX, oldMouseY);
        }
        
        turnDelta += controllerAxisX * 2.0f * time.delta;
        
        targetTurnAngle += turnDelta;
        float delta = shortestAngleDelta(turnAngle, targetTurnAngle);
        turnAngle += delta * turnStiffness;
        
        pitchDelta += -controllerAxisY * 2.0f * time.delta;
        
        targetPitchAngle += pitchDelta;
        targetPitchAngle = clamp(targetPitchAngle, degtorad(10.0f), degtorad(40.0f));
        pitchAngle += (targetPitchAngle - pitchAngle) * pitchStiffness;
        
        Vector3f carDirection = target.direction;
        carDirection = Vector3f(carDirection.x, 0.0f, carDirection.z).normalized;
        float targetCarViewTurnAngle = -(atan2(carDirection.z, carDirection.x) - PI * 0.5f);
        delta = shortestAngleDelta(carViewTurnAngle, targetCarViewTurnAngle);
        carViewTurnAngle += delta * 1.5f * time.delta;
        
        Quaternionf carRotation =
            rotationQuaternion(Vector3f(0, 1, 0), carViewTurnAngle);

        Quaternionf mouseRotation =
            rotationQuaternion(Vector3f(0, 1, 0), turnAngle) *
            rotationQuaternion(Vector3f(1, 0, 0), pitchAngle);

        Quaternionf finalRotation = carRotation * mouseRotation;
        
        Vector3f offset = finalRotation.rotate(Vector3f(0.0f, 0.0f, 1.0f)).normalized;
        
        smoothTargetDistance += (targetDistance - smoothTargetDistance) * zoomStiffness;
        Vector3f cameraPosition = target.position + offset * -smoothTargetDistance;
        
        Vector3f viewFrom = cameraPosition;
        Vector3f viewTo = target.position + Vector3f(0, 1.0f, 0);
        Vector3f viewDir = (viewTo - viewFrom).normalized;
        Vector3f viewUp = Vector3f(0, 1, 0);
        Vector3f viewRight = cross(viewDir, viewUp);
        
        Matrix4x4f trans = lookAtMatrix(viewFrom, viewTo, Vector3f(0, 1, 0));
        
        entity.transformation = trans.inverse;
        entity.invTransformation = trans;
        
        entity.absoluteTransformation = entity.transformation;
        entity.invAbsoluteTransformation = entity.invTransformation;
        entity.prevAbsoluteTransformation = entity.prevTransformation;
    }
    
    override void onMouseWheel(int x, int y)
    {
        if (!mouseActive || !mouseGrab)
            return;
        
        float zoom = cast(float)y * mouseZoomSensibility;
        targetDistance -= zoom;
        targetDistance = clamp(targetDistance, minDistanceToTarget, maxDistanceToTarget);
    }
    
    override void onFocusLoss()
    {
        mouseGrab = false;
    }
    
    override void onFocusGain()
    {
        mouseGrab = true;
    }
}
