/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module track;

import dlib.core.ownership;
import dlib.container.array;
import dlib.math.vector;

struct GroundMaterial
{
    float grip = 1.0f;
    float rollingResistanceC0 = 0.001f;
    float rollingResistanceC1 = 0.001f;
    float rollingResistanceC2 = 0.000f;
}

class Track: Owner
{
    ///
    Vector3f[] waypoints;
    
    ///
    Array!GroundMaterial materials;
    
    ///
    uint numLaps = 3;
    
    this(Owner owner)
    {
        super(owner);
    }
    
    ~this()
    {
        materials.free();
    }
    
    void addMaterial(GroundMaterial m)
    {
        materials.append(m);
    }
    
    size_t getNearestSegmentIndex(size_t currentSegmentIndex, Vector3f carPosition)
    {
        // Update the current segment (search for the closest point to the car within a small range).
        // Limit the search to the vicinity of the old index so it doesn't jump to the finish line
        size_t searchStart = (currentSegmentIndex > 2) ? currentSegmentIndex - 2 : 0;
        size_t searchEnd = currentSegmentIndex + 5;
        if (searchEnd >= waypoints.length) searchEnd = waypoints.length;
        
        float minD = float.max;
        size_t bestIdx = currentSegmentIndex;

        for (size_t i = searchStart; i < searchEnd; ++i)
        {
            float distSq = (carPosition.x - waypoints[i].x)^^2 + (carPosition.z - waypoints[i].z)^^2;
            if (distSq < minD)
            {
                minD = distSq;
                bestIdx = i;
            }
        }
        
        // Segment index is the index of the starting point of the segment
        if (bestIdx < waypoints.length - 1)
            return bestIdx;
        else
            return 0; // Looping the index when crossing the finish line
    }
}
