/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module ui;

import std.stdio;

import dagon.core.bindings;
import dagon.core.application;
import dagon.core.event;
import dagon.core.time;
import dagon.ext.imgui;

import race;

class ImGui: EventListener
{
    Application application;
    RaceScene scene;
    
    ImGuiContext* igContext;
    ImGuiIO* io;
    ImFont* font;
    bool active = false;
    
    bool showRestartPopup = false;
    bool showExitPopup = false;
    
    this(Application application, RaceScene scene)
    {
        super(application.eventManager, application);
        this.application = application;
        
        igContext = igCreateContext(null);
        igSetCurrentContext(igContext);
        io = igGetIO();
        io.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
        io.ConfigFlags |= ImGuiConfigFlags.NoMouseCursorChange;
        io.ConfigWindowsMoveFromTitleBarOnly = true;
        ImWchar[] ranges = [
            0x0020, 0x00FF, // Basic Latin + Latin Supplement
            0x0370, 0x03FF, // Greek
            0x0400, 0x044F, // Cyrillic
            0
        ];
        font = ImFontAtlas_AddFontFromFileTTF(io.Fonts, "data/font/DroidSans.ttf", 20, null, ranges.ptr);
        igStyleColorsDark(null);
        applyTheme();
        ImGui_ImplSDL2_InitForOpenGL(application.window, application.glcontext);
        ImGuiOpenGLBackend.init("#version 400 core");
        
        this.scene = scene;
    }
    
    void onProcessEvent(SDL_Event* event)
    {
        if (active)
            ImGui_ImplSDL2_ProcessEvent(event);
    }
    
    bool capturesMouse() @property
    {
        return active && io.WantCaptureMouse;
    }
    
    bool capturesKeyboard() @property
    {
        return active && io.WantCaptureKeyboard;
    }
    
    void update(Time t)
    {
        if (!active)
            return;
        
        processEvents();
        
        ImGuiOpenGLBackend.new_frame();
        ImGui_ImplSDL2_NewFrame();
        igNewFrame();
        
        drawPauseUI();
        
        igRender();
    }
    
    void drawPauseUI()
    {
        if (igBegin("Pause", null, ImGuiWindowFlags.NoCollapse))
        {
            if (igButton("Resume", ImVec2(100, 32)))
            {
                scene.togglePause();
            }
            
            igSameLine(0.0f, -1.0f);
            
            if (igButton("Restart", ImVec2(100, 32)))
            {
                igOpenPopup("Restart Confirmation");
                showRestartPopup = true;
            }
            
            igSameLine(0.0f, -1.0f);
            
            if (igButton("Exit", ImVec2(100, 32)))
            {
                igOpenPopup("Exit Confirmation");
                showExitPopup = true;
            }
        }
        
        if (igBegin("Car settings", null, ImGuiWindowFlags.NoCollapse))
        {
            if (igCollapsingHeader("Paint", ImGuiTreeNodeFlags.DefaultOpen))
            {
                auto mat = scene.car.carPaintMaterial;
                if (mat)
                {
                    igColorEdit4("Color", &mat.baseColorFactor.arrayof, ImGuiColorEditFlags.Float);
                    igSliderFloat("Roughness", &mat.roughnessFactor, 0.0f, 1.0f, "%.3f");
                    igSliderFloat("Metallic", &mat.metallicFactor, 0.0f, 1.0f, "%.3f");
                }
            }
            
            igEnd();
        }
        
        if (igBegin("Quick options", null, ImGuiWindowFlags.NoCollapse))
        {
            igCheckbox("Enable gamepad rumble", &scene.rumbleEnabled);
            
            igEnd();
        }
        
        if (igBegin("Standings", null, ImGuiWindowFlags.NoCollapse))
        {
            ImGuiTableFlags flags = ImGuiTableFlags.RowBg | 
                                    ImGuiTableFlags.BordersOuter | 
                                    ImGuiTableFlags.BordersV | 
                                    ImGuiTableFlags.NoBordersInBody;

            if (igBeginTable("LeaderboardTable", 4, flags, ImVec2(0.0f, 0.0f), 0.0f))
            {
                // Column headers
                igTableSetupColumn("Pos.", ImGuiTableColumnFlags.WidthFixed, 40.0f, 0);
                igTableSetupColumn("Racer", ImGuiTableColumnFlags.WidthStretch, 0.0f, 0);
                igTableSetupColumn("Lap", ImGuiTableColumnFlags.WidthFixed, 100.0f, 0);
                igTableSetupColumn("Best lap", ImGuiTableColumnFlags.WidthFixed, 100.0f, 0);
                igTableHeadersRow();

                // Populate rows with data
                foreach (i, car; scene.participants)
                {
                    igTableNextRow(ImGuiTableRowFlags.None, 0.0f);

                    // Highlight the player's row
                    if (car.isPlayer)
                        igTableSetBgColor(ImGuiTableBgTarget.RowBg0, 
                            igColorConvertFloat4ToU32(ImVec4(0.9f, 0.45f, 0.0f, 0.25f)), -1);

                    // Column 0: Position
                    igTableSetColumnIndex(0);
                    char[8] posStr;
                    snprintf(posStr.ptr, posStr.length, "%d", car.racePosition);
                    posStr[7] = '\0';
                    
                    // Make top 3 positions pop out color-wise
                    if (car.racePosition == 1)
                        igTextColored(ImVec4(1.0f, 0.84f, 0.0f, 1.0f), posStr.ptr); // Gold
                    else if (car.racePosition == 2)
                        igTextColored(ImVec4(0.75f, 0.75f, 0.75f, 1.0f), posStr.ptr); // Silver
                    else if (car.racePosition == 3)
                        igTextColored(ImVec4(0.8f, 0.5f, 0.2f, 1.0f), posStr.ptr); // Bronze
                    else
                        igText(posStr.ptr);

                    // Column 1: Name
                    igTableSetColumnIndex(1);
                    if (car.isPlayer)
                        igTextColored(ImVec4(1.0f, 0.55f, 0.15f, 1.0f), car.name.ptr); // Bright Orange text for player
                    else
                        igText(car.name.ptr);

                    // Column 2: Current Lap Time
                    igTableSetColumnIndex(2);
                    char[11] timeStr;
                    uint lapMin = cast(uint)(car.lapTime / 60.0);
                    uint lapSec = cast(uint)(car.lapTime) % 60;
                    uint lapMsec = cast(uint)((car.lapTime - cast(uint)car.lapTime) * 1000.0);
                    uint n = sprintf(timeStr.ptr, "%02u:%02u.%03u\0", lapMin, lapSec, lapMsec);
                    igText(timeStr.ptr);

                    // Column 3: Best Lap Time
                    igTableSetColumnIndex(3);
                    char[11] bestTimeStr;
                    uint bestMin = cast(uint)(car.bestLapTime / 60.0);
                    uint bestSec = cast(uint)(car.bestLapTime) % 60;
                    uint bestMsec = cast(uint)((car.bestLapTime - cast(uint)car.bestLapTime) * 1000.0);
                    n = sprintf(bestTimeStr.ptr, "%02u:%02u.%03u\0", bestMin, bestSec, bestMsec);
                    igTextColored(ImVec4(0.0f, 0.9f, 0.4f, 1.00), bestTimeStr.ptr); // Green text for best times
                }

                igEndTable();
            }
            
            igEnd();
        }
        
        if (igBeginPopupModal("Exit Confirmation", null, ImGuiWindowFlags.AlwaysAutoResize))
        {
            igText("Are you sure you want to quit?");
            igSeparator();

            if (igButton("Yes", ImVec2(120, 0)))
            {
                application.exit();
                
                igCloseCurrentPopup();
                showExitPopup = false;
            }
            
            igSameLine(0.0f, -1.0f);
            
            if (igButton("Cancel", ImVec2(120, 0)))
            {
                igCloseCurrentPopup();
                showExitPopup = false;
            }
            
            igEndPopup();
        }
        
        if (igBeginPopupModal("Restart Confirmation", null, ImGuiWindowFlags.AlwaysAutoResize))
        {
            igText("Are you sure you want to restart?");
            igSeparator();

            if (igButton("Yes", ImVec2(120, 0)))
            {
                scene.restartRace();
                
                igCloseCurrentPopup();
                showRestartPopup = false;
            }
            
            igSameLine(0.0f, -1.0f);
            
            if (igButton("Cancel", ImVec2(120, 0)))
            {
                igCloseCurrentPopup();
                showRestartPopup = false;
            }
            
            igEndPopup();
        }
    }
    
    void render()
    {
        if (active)
            ImGuiOpenGLBackend.render_draw_data(igGetDrawData());
    }
    
    void applyTheme()
    {
        // 1. Fetch the global style reference
        ImGuiStyle* style = igGetStyle();
        
        // 2. Apply modern window and widget rounding
        style.WindowRounding    = 6.0f;
        style.ChildRounding     = 4.0f;
        style.FrameRounding     = 4.0f;
        style.PopupRounding     = 4.0f;
        style.ScrollbarRounding = 9.0f;
        style.GrabRounding      = 4.0f;
        style.TabRounding       = 4.0f;

        // 3. Define our color palette
        ImVec4 color_bg_dark     = ImVec4(0.10f, 0.10f, 0.10f, 0.75f); // Deep charcoal
        ImVec4 color_bg_med      = ImVec4(0.15f, 0.15f, 0.15f, 0.8f); // Lighter panel background
        ImVec4 color_bg_light    = ImVec4(0.22f, 0.22f, 0.22f, 1.0f); // Interactive element background
        
        ImVec4 color_orange      = ImVec4(0.90f, 0.45f, 0.00f, 1.0f); // Vibrant orange
        ImVec4 color_orange_hover= ImVec4(1.00f, 0.55f, 0.15f, 1.0f); // Bright orange for hover
        ImVec4 color_orange_act  = ImVec4(0.80f, 0.35f, 0.00f, 1.0f); // Deeper orange for clicks

        ImVec4 color_text        = ImVec4(0.95f, 0.95f, 0.95f, 1.0f); // Off-white text
        ImVec4 color_text_disabled=ImVec4(0.50f, 0.50f, 0.50f, 1.0f); 

        // 4. Map colors to ImGui elements
        style.Colors[ImGuiCol.Text]                  = color_text;
        style.Colors[ImGuiCol.TextDisabled]          = color_text_disabled;
        
        // Window Backgrounds
        style.Colors[ImGuiCol.WindowBg]              = color_bg_dark;
        style.Colors[ImGuiCol.ChildBg]               = color_bg_med;
        style.Colors[ImGuiCol.PopupBg]               = color_bg_dark;
        style.Colors[ImGuiCol.Border]                = ImVec4(0.25f, 0.25f, 0.25f, 1.00f);
        style.Colors[ImGuiCol.BorderShadow]          = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);

        // Frame Elements (Checkboxes, Input Fields, etc.)
        style.Colors[ImGuiCol.FrameBg]               = color_bg_light;
        style.Colors[ImGuiCol.FrameBgHovered]        = ImVec4(0.28f, 0.28f, 0.28f, 1.00f);
        style.Colors[ImGuiCol.FrameBgActive]         = ImVec4(0.35f, 0.35f, 0.35f, 1.00f);

        // Headers (Collapsing Headers, Tree Nodes)
        style.Colors[ImGuiCol.Header]                = color_bg_light;
        style.Colors[ImGuiCol.HeaderHovered]         = color_orange;
        style.Colors[ImGuiCol.HeaderActive]          = color_orange_act;

        // Buttons (The main orange highlights)
        style.Colors[ImGuiCol.Button]                = color_orange;
        style.Colors[ImGuiCol.ButtonHovered]         = color_orange_hover;
        style.Colors[ImGuiCol.ButtonActive]          = color_orange_act;

        // Window Titles
        style.Colors[ImGuiCol.TitleBg]               = color_bg_med;
        style.Colors[ImGuiCol.TitleBgActive]          = color_bg_med;
        style.Colors[ImGuiCol.TitleBgCollapsed]       = color_bg_dark;

        // Tabs
        style.Colors[ImGuiCol.Tab]                   = color_bg_med;
        style.Colors[ImGuiCol.TabHovered]            = color_orange_hover;
        style.Colors[ImGuiCol.TabActive]             = color_orange;
        style.Colors[ImGuiCol.TabUnfocused]          = color_bg_med;
        style.Colors[ImGuiCol.TabUnfocusedActive]     = color_bg_light;

        // Sliders & Scrollbars
        style.Colors[ImGuiCol.ScrollbarBg]           = color_bg_dark;
        style.Colors[ImGuiCol.ScrollbarGrab]         = color_bg_light;
        style.Colors[ImGuiCol.ScrollbarGrabHovered]  = ImVec4(0.30f, 0.30f, 0.30f, 1.00f);
        style.Colors[ImGuiCol.ScrollbarGrabActive]   = color_orange;
        style.Colors[ImGuiCol.CheckMark]             = color_orange;
        style.Colors[ImGuiCol.SliderGrab]            = color_orange;
        style.Colors[ImGuiCol.SliderGrabActive]      = color_orange_act;

        // Miscellaneous
        style.Colors[ImGuiCol.ResizeGrip]            = color_bg_light;
        style.Colors[ImGuiCol.ResizeGripHovered]     = color_orange;
        style.Colors[ImGuiCol.ResizeGripActive]      = color_orange_act;
        style.Colors[ImGuiCol.Separator]             = ImVec4(0.20f, 0.20f, 0.20f, 1.00f);
        style.Colors[ImGuiCol.SeparatorHovered]      = color_orange;
        style.Colors[ImGuiCol.SeparatorActive]       = color_orange_act;
        style.Colors[ImGuiCol.TextSelectedBg]        = ImVec4(0.90f, 0.45f, 0.00f, 0.35f); // Semi-transparent orange selection
    }
}
