/*
Copyright (c) 2021-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module view;

import std.math;
import std.random;

import dagon;
import vehicle;

class VehicleViewComponent: EntityComponent
{
    Vehicle vehicle;
    
    int oldMouseX;
    int oldMouseY;
    
    float targetTurnAngle = 0.0f;
    float turnAngle = 0.0f;
    
    bool active = true;
    bool mouseActive = true;
    
    float mouseSensibility = 0.2f;

    this(EventManager em, Entity e, Vehicle vehicle)
    {
        super(em, e);
        
        this.vehicle = vehicle;
        
        oldMouseX = eventManager.windowWidth / 2;
        oldMouseY = eventManager.windowHeight / 2;
    }
    
    override void update(Time time)
    {
        processEvents();
        
        float turnDelta = 0.0f;
        if (active & mouseActive)
        {
            turnDelta = (eventManager.mouseX - oldMouseX) * mouseSensibility * time.delta;
            eventManager.setMouse(oldMouseX, oldMouseY);
        }
        
        targetTurnAngle += turnDelta;
        turnAngle += (targetTurnAngle - turnAngle) * 0.2f;
        Quaternionf mouseRotation = rotationQuaternion!float(Axis.y, turnAngle);
        Vector3f offset = mouseRotation.rotate(Vector3f(0.0f, 0.0f, 1.0f));
        
        Vector3f cameraPosition = (offset.normalized * -4.7f) * vehicle.transformation;
        cameraPosition.y = vehicle.position.y + 1.6f;
        
        Vector3f viewFrom = cameraPosition;
        Vector3f viewTo = vehicle.position + Vector3f(0, 1.0f, 0);
        Vector3f viewDir = (viewTo - viewFrom).normalized;
        Vector3f viewUp = Vector3f(0, 1, 0);
        Vector3f viewRight = cross(viewDir, viewUp);
        
        Matrix4x4f trans = lookAtMatrix(viewFrom, viewTo, Vector3f(0, 1, 0));
        
        entity.transformation = trans.inverse;
        entity.invTransformation = trans;
        
        entity.absoluteTransformation = entity.transformation;
        entity.invAbsoluteTransformation = entity.invTransformation;
        entity.prevAbsoluteTransformation = entity.prevTransformation;
    }
}
